import type { InventoryItemDefinition, ItemDefinition } from "../types/itemTypes";

export const INVENTORY_ITEM_CATEGORY = Object.freeze({
  MATERIAL: "material",
  CONSUMABLE: "consumable",
  EQUIPMENT: "equipment",
  OTHER: "other",
});

export const PROFESSION_ITEM_DEFINITIONS = Object.freeze({
  linen_cloth: {
    id: "linen_cloth",
    name: "Linen Cloth",
    category: INVENTORY_ITEM_CATEGORY.MATERIAL,
    quality: 1,
    professionTags: ["Tailoring"],
    source: "Tailoring",
    sellValue: 1,
  },
  wool_cloth: {
    id: "wool_cloth",
    name: "Wool Cloth",
    category: INVENTORY_ITEM_CATEGORY.MATERIAL,
    quality: 1,
    professionTags: ["Tailoring"],
    source: "Tailoring",
    sellValue: 2,
  },
  silk_cloth: {
    id: "silk_cloth",
    name: "Silk Cloth",
    category: INVENTORY_ITEM_CATEGORY.MATERIAL,
    quality: 1,
    professionTags: ["Tailoring"],
    source: "Tailoring",
    sellValue: 3,
  },
  light_leather: {
    id: "light_leather",
    name: "Light Leather",
    category: INVENTORY_ITEM_CATEGORY.MATERIAL,
    quality: 1,
    professionTags: ["Leatherworking", "Skinning"],
    source: "Skinning",
    sellValue: 1,
  },
  medium_leather: {
    id: "medium_leather",
    name: "Medium Leather",
    category: INVENTORY_ITEM_CATEGORY.MATERIAL,
    quality: 1,
    professionTags: ["Leatherworking", "Skinning"],
    source: "Skinning",
    sellValue: 2,
  },
  heavy_leather: {
    id: "heavy_leather",
    name: "Heavy Leather",
    category: INVENTORY_ITEM_CATEGORY.MATERIAL,
    quality: 1,
    professionTags: ["Leatherworking", "Skinning"],
    source: "Skinning",
    sellValue: 3,
  },
  peacebloom: {
    id: "peacebloom",
    name: "Peacebloom",
    category: INVENTORY_ITEM_CATEGORY.MATERIAL,
    quality: 1,
    professionTags: ["Alchemy", "Herbalism"],
    source: "Herbalism",
    sellValue: 1,
  },
  silverleaf: {
    id: "silverleaf",
    name: "Silverleaf",
    category: INVENTORY_ITEM_CATEGORY.MATERIAL,
    quality: 1,
    professionTags: ["Alchemy", "Herbalism"],
    source: "Herbalism",
    sellValue: 1,
  },
  briarthorn: {
    id: "briarthorn",
    name: "Briarthorn",
    category: INVENTORY_ITEM_CATEGORY.MATERIAL,
    quality: 1,
    professionTags: ["Alchemy", "Herbalism"],
    source: "Herbalism",
    sellValue: 2,
  },
  empty_vial: {
    id: "empty_vial",
    name: "Empty Vial",
    category: INVENTORY_ITEM_CATEGORY.MATERIAL,
    quality: 1,
    professionTags: ["Alchemy"],
    source: "Vendor",
    sellValue: 1,
  },
  simple_thread: {
    id: "simple_thread",
    name: "Simple Thread",
    category: INVENTORY_ITEM_CATEGORY.MATERIAL,
    quality: 1,
    professionTags: ["Tailoring"],
    source: "Vendor",
    sellValue: 1,
  },
  coarse_thread: {
    id: "coarse_thread",
    name: "Coarse Thread",
    category: INVENTORY_ITEM_CATEGORY.MATERIAL,
    quality: 1,
    professionTags: ["Tailoring", "Leatherworking"],
    source: "Vendor",
    sellValue: 1,
  },
  minor_healing_potion: {
    id: "minor_healing_potion",
    name: "Minor Healing Potion",
    category: INVENTORY_ITEM_CATEGORY.CONSUMABLE,
    quality: 1,
    effect: "minor_healing_potion",
    source: "Alchemy",
    sellValue: 2,
  },
  healing_potion: {
    id: "healing_potion",
    name: "Healing Potion",
    category: INVENTORY_ITEM_CATEGORY.CONSUMABLE,
    quality: 2,
    effect: "healing_potion",
    source: "Alchemy",
    sellValue: 4,
  },
  elixir_of_fortitude: {
    id: "elixir_of_fortitude",
    name: "Elixir of Fortitude",
    category: INVENTORY_ITEM_CATEGORY.CONSUMABLE,
    quality: 2,
    effect: "elixir_of_fortitude",
    source: "Alchemy",
    sellValue: 5,
  },
  elixir_of_power: {
    id: "elixir_of_power",
    name: "Elixir of Power",
    category: INVENTORY_ITEM_CATEGORY.CONSUMABLE,
    quality: 2,
    effect: "elixir_of_power",
    source: "Alchemy",
    sellValue: 5,
  },
  apprentice_cloth_robe: {
    id: "apprentice_cloth_robe",
    name: "Apprentice Cloth Robe",
    category: INVENTORY_ITEM_CATEGORY.EQUIPMENT,
    quality: 2,
    slot: "chest",
    armorType: "Cloth",
    type: "Cloth",
    minLevel: 8,
    levelRequirement: 8,
    itemLevel: 16,
    stats: { intellect: 2, spirit: 1 },
    source: "Tailoring",
    profession: "Tailoring",
    sellValue: 3,
  },
  mystic_woolen_gloves: {
    id: "mystic_woolen_gloves",
    name: "Mystic Woolen Gloves",
    category: INVENTORY_ITEM_CATEGORY.EQUIPMENT,
    quality: 2,
    slot: "hands",
    armorType: "Cloth",
    type: "Cloth",
    minLevel: 22,
    levelRequirement: 22,
    itemLevel: 32,
    stats: { intellect: 4, spirit: 2 },
    source: "Tailoring",
    profession: "Tailoring",
    sellValue: 6,
  },
  runecloth_mantle: {
    id: "runecloth_mantle",
    name: "Runecloth Mantle",
    category: INVENTORY_ITEM_CATEGORY.EQUIPMENT,
    quality: 3,
    slot: "shoulder",
    armorType: "Cloth",
    type: "Cloth",
    minLevel: 48,
    levelRequirement: 48,
    itemLevel: 58,
    stats: { intellect: 8, spirit: 5, stamina: 4 },
    source: "Tailoring",
    profession: "Tailoring",
    sellValue: 12,
  },
  stitched_leather_vest: {
    id: "stitched_leather_vest",
    name: "Stitched Leather Vest",
    category: INVENTORY_ITEM_CATEGORY.EQUIPMENT,
    quality: 2,
    slot: "chest",
    armorType: "Leather",
    type: "Leather",
    minLevel: 10,
    levelRequirement: 10,
    itemLevel: 18,
    stats: { agility: 2, stamina: 2 },
    source: "Leatherworking",
    profession: "Leatherworking",
    sellValue: 3,
  },
  rangers_hunting_gloves: {
    id: "rangers_hunting_gloves",
    name: "Ranger's Hunting Gloves",
    category: INVENTORY_ITEM_CATEGORY.EQUIPMENT,
    quality: 2,
    slot: "hands",
    armorType: "Leather",
    type: "Leather",
    minLevel: 26,
    levelRequirement: 26,
    itemLevel: 36,
    stats: { agility: 5, stamina: 3 },
    source: "Leatherworking",
    profession: "Leatherworking",
    sellValue: 7,
  },
  wildhide_boots: {
    id: "wildhide_boots",
    name: "Wildhide Boots",
    category: INVENTORY_ITEM_CATEGORY.EQUIPMENT,
    quality: 3,
    slot: "feet",
    armorType: "Leather",
    type: "Leather",
    minLevel: 46,
    levelRequirement: 46,
    itemLevel: 56,
    stats: { agility: 8, stamina: 5 },
    source: "Leatherworking",
    profession: "Leatherworking",
    sellValue: 12,
  },
} satisfies Record<string, InventoryItemDefinition>);

const INVENTORY_DEFINITIONS_BY_ID: Readonly<Record<string, InventoryItemDefinition>> =
  PROFESSION_ITEM_DEFINITIONS;

export const getInventoryItemDefinition = (itemId: unknown): InventoryItemDefinition | null =>
  INVENTORY_DEFINITIONS_BY_ID[String(itemId || "").trim()] || null;

export const getAllInventoryItemDefinitions = () =>
  Object.values(PROFESSION_ITEM_DEFINITIONS);

export const toEquipmentItem = (
  definition: InventoryItemDefinition | null | undefined,
): ItemDefinition | null => {
  if (!definition || definition.category !== INVENTORY_ITEM_CATEGORY.EQUIPMENT) {
    return null;
  }
  return {
    id: definition.id,
    name: definition.name,
    slot: definition.slot,
    type: definition.armorType || definition.type || "Generic",
    quality: definition.quality,
    minLevel: definition.levelRequirement || definition.minLevel || 1,
    itemLevel: definition.itemLevel || definition.gearScore,
    stats: definition.stats || {},
    source: definition.source,
    profession: definition.profession,
    crafted: true,
    sellValue: definition.sellValue || 0,
    allowedClasses: Array.isArray(definition.classRestrictions)
      ? definition.classRestrictions
      : undefined,
  };
};
