import {
  BookOpen,
  CalendarDays,
  Castle,
  ClipboardList,
  Hammer,
  Home,
  Map,
  ScrollText,
  Shield,
  Swords,
  Trophy,
  UserPlus,
} from "lucide-react";

import { ROUTES } from "../../routes";
import type { NavigationItem } from "./navigationTypes";

type HomeNavigationOptions = {
  applicationCount: number;
  activeDungeonCount: number;
  activeBattlefieldCount: number;
};

export const buildHomeNavigation = ({
  applicationCount,
  activeDungeonCount,
  activeBattlefieldCount,
}: HomeNavigationOptions): NavigationItem[] => [
  {
    id: "home",
    label: "Home",
    icon: Home,
    group: "overview",
    kind: "route",
    to: ROUTES.DASHBOARD,
    mobilePrimary: true,
    mobileOrder: 1,
  },
  {
    id: "guild",
    label: "Guild",
    icon: Shield,
    group: "overview",
    kind: "route",
    to: ROUTES.GUILD,
  },
  {
    id: "recruit",
    label: "Recruit",
    icon: UserPlus,
    group: "overview",
    kind: "route",
    to: ROUTES.RECRUIT,
    badge: applicationCount,
    badgeTone: "amber",
    tone: "primary",
    mobilePrimary: true,
    mobileOrder: 4,
  },
  {
    id: "missions",
    label: "Missions",
    icon: ScrollText,
    group: "activities",
    kind: "route",
    to: ROUTES.MISSION_BOARD,
    tone: "quest",
    mobilePrimary: true,
    mobileOrder: 2,
  },
  {
    id: "adventure",
    label: "Adventure Board",
    shortLabel: "Adventure",
    icon: Map,
    group: "activities",
    kind: "route",
    to: ROUTES.ADVENTURE_BOARD,
    tone: "success",
    mobilePrimary: true,
    mobileOrder: 3,
  },
  {
    id: "dungeons",
    label: "Dungeon Board",
    shortLabel: "Dungeons",
    icon: Swords,
    group: "activities",
    kind: "route",
    to: ROUTES.DUNGEON_BOARD,
    badge: activeDungeonCount,
    badgeTone: "cyan",
  },
  {
    id: "battlefields",
    label: "Battlefields",
    icon: Trophy,
    group: "activities",
    kind: "route",
    to: ROUTES.BATTLEFIELDS,
    badge: activeBattlefieldCount,
    badgeTone: "red",
    tone: "danger",
  },
  {
    id: "calendar",
    label: "Calendar",
    icon: CalendarDays,
    group: "world",
    kind: "route",
    to: ROUTES.CALENDAR,
  },
  {
    id: "realm",
    label: "Realm",
    icon: Castle,
    group: "world",
    kind: "route",
    to: ROUTES.REALM,
  },
  {
    id: "professions",
    label: "Professions",
    icon: Hammer,
    group: "tools",
    kind: "route",
    to: ROUTES.PROFESSIONS,
    tone: "success",
  },
  {
    id: "database",
    label: "Database",
    shortLabel: "DB",
    icon: BookOpen,
    group: "tools",
    kind: "route",
    to: ROUTES.DATABASE,
  },
  {
    id: "log",
    label: "Guild Log",
    shortLabel: "Log",
    icon: ClipboardList,
    group: "tools",
    kind: "route",
    to: ROUTES.GUILD_LOG,
  },
];
