export const ZONE_MAP_LAYOUT_BY_ZONE_ID = Object.freeze({
  teldrassil: { x: 13, y: 20, continent: "Kalimdor" },
  darkshore: { x: 18, y: 30, continent: "Kalimdor" },
  moonglade: { x: 36, y: 18, continent: "Kalimdor" },
  winterspring: { x: 46, y: 18, continent: "Kalimdor" },
  felwood: { x: 34, y: 29, continent: "Kalimdor" },
  azshara: { x: 48, y: 31, continent: "Kalimdor" },
  ashenvale: { x: 31, y: 39, continent: "Kalimdor" },
  stonetalon_mountains: { x: 25, y: 48, continent: "Kalimdor" },
  the_barrens: { x: 36, y: 55, continent: "Kalimdor" },
  durotar: { x: 49, y: 50, continent: "Kalimdor" },
  mulgore: { x: 30, y: 66, continent: "Kalimdor" },
  thousand_needles: { x: 38, y: 72, continent: "Kalimdor" },
  desolace: { x: 20, y: 63, continent: "Kalimdor" },
  feralas: { x: 24, y: 80, continent: "Kalimdor" },
  dustwallow_marsh: { x: 48, y: 72, continent: "Kalimdor" },
  tanaris: { x: 43, y: 86, continent: "Kalimdor" },
  un_goro_crater: { x: 34, y: 88, continent: "Kalimdor" },
  silithus: { x: 22, y: 88, continent: "Kalimdor" },

  dun_morogh: { x: 73, y: 77, continent: "Eastern Kingdoms" },
  elwynn_forest: { x: 77, y: 68, continent: "Eastern Kingdoms" },
  westfall: { x: 73, y: 74, continent: "Eastern Kingdoms" },
  redridge_mountains: { x: 82, y: 68, continent: "Eastern Kingdoms" },
  duskwood: { x: 78, y: 74, continent: "Eastern Kingdoms" },
  loch_modan: { x: 78, y: 59, continent: "Eastern Kingdoms" },
  wetlands: { x: 75, y: 51, continent: "Eastern Kingdoms" },
  arathi_highlands: { x: 75, y: 43, continent: "Eastern Kingdoms" },
  hillsbrad_foothills: { x: 72, y: 35, continent: "Eastern Kingdoms" },
  alterac_mountains: { x: 74, y: 31, continent: "Eastern Kingdoms" },
  silverpine_forest: { x: 69, y: 29, continent: "Eastern Kingdoms" },
  tirisfal_glades: { x: 73, y: 22, continent: "Eastern Kingdoms" },
  western_plaguelands: { x: 80, y: 25, continent: "Eastern Kingdoms" },
  eastern_plaguelands: { x: 87, y: 23, continent: "Eastern Kingdoms" },
  the_hinterlands: { x: 83, y: 38, continent: "Eastern Kingdoms" },
  searing_gorge: { x: 78, y: 63, continent: "Eastern Kingdoms" },
  burning_steppes: { x: 82, y: 65, continent: "Eastern Kingdoms" },
  badlands: { x: 83, y: 58, continent: "Eastern Kingdoms" },
  swamp_of_sorrows: { x: 86, y: 75, continent: "Eastern Kingdoms" },
  blasted_lands: { x: 83, y: 82, continent: "Eastern Kingdoms" },
  deadwind_pass: { x: 82, y: 72, continent: "Eastern Kingdoms" },
  stranglethorn_vale_north: { x: 76, y: 83, continent: "Eastern Kingdoms" },
  stranglethorn_vale_south: { x: 77, y: 91, continent: "Eastern Kingdoms" },
});

export const getZoneMapLayout = (zoneId) =>
  ZONE_MAP_LAYOUT_BY_ZONE_ID[zoneId] ?? { x: 50, y: 50, continent: "Azeroth" };

const ZONE_CLASSIC_MAP_BY_ZONE_ID = Object.freeze({
  teldrassil: { mapId: 141, slug: "teldrassil" },
  dun_morogh: { mapId: 1, slug: "dun-morogh" },
  elwynn_forest: { mapId: 12, slug: "elwynn-forest" },
  durotar: { mapId: 14, slug: "durotar" },
  mulgore: { mapId: 215, slug: "mulgore" },
  tirisfal_glades: { mapId: 85, slug: "tirisfal-glades" },
  darkshore: { mapId: 148, slug: "darkshore" },
  loch_modan: { mapId: 38, slug: "loch-modan" },
  westfall: { mapId: 40, slug: "westfall" },
  silverpine_forest: { mapId: 130, slug: "silverpine-forest" },
  the_barrens: { mapId: 17, slug: "the-barrens" },
  redridge_mountains: { mapId: 44, slug: "redridge-mountains" },
  stonetalon_mountains: { mapId: 406, slug: "stonetalon-mountains" },
  ashenvale: { mapId: 331, slug: "ashenvale" },
  duskwood: { mapId: 10, slug: "duskwood" },
  hillsbrad_foothills: { mapId: 267, slug: "hillsbrad-foothills" },
  wetlands: { mapId: 11, slug: "wetlands" },
  thousand_needles: { mapId: 400, slug: "thousand-needles" },
  alterac_mountains: { mapId: 36, slug: "alterac-mountains" },
  arathi_highlands: { mapId: 45, slug: "arathi-highlands" },
  desolace: { mapId: 405, slug: "desolace" },
  stranglethorn_vale_north: { mapId: 33, slug: "stranglethorn-vale" },
  stranglethorn_vale_south: { mapId: 33, slug: "stranglethorn-vale" },
  badlands: { mapId: 3, slug: "badlands" },
  dustwallow_marsh: { mapId: 15, slug: "dustwallow-marsh" },
  swamp_of_sorrows: { mapId: 8, slug: "swamp-of-sorrows" },
  feralas: { mapId: 357, slug: "feralas" },
  the_hinterlands: { mapId: 47, slug: "the-hinterlands" },
  tanaris: { mapId: 440, slug: "tanaris" },
  searing_gorge: { mapId: 51, slug: "searing-gorge" },
  azshara: { mapId: 16, slug: "azshara" },
  felwood: { mapId: 361, slug: "felwood" },
  un_goro_crater: { mapId: 490, slug: "un-goro-crater" },
  blasted_lands: { mapId: 4, slug: "blasted-lands" },
  burning_steppes: { mapId: 46, slug: "burning-steppes" },
  western_plaguelands: { mapId: 28, slug: "western-plaguelands" },
  eastern_plaguelands: { mapId: 139, slug: "eastern-plaguelands" },
  winterspring: { mapId: 618, slug: "winterspring" },
  moonglade: { mapId: 493, slug: "moonglade" },
  deadwind_pass: { mapId: 41, slug: "deadwind-pass" },
  silithus: { mapId: 1377, slug: "silithus" },
});

const getClassicMapConfig = (zone) => ZONE_CLASSIC_MAP_BY_ZONE_ID[zone?.id] ?? null;

export const getZoneRegionalMap = (zone) => {
  const classicMap = getClassicMapConfig(zone);
  if (!classicMap) return null;

  return {
    mapId: classicMap.mapId,
    sourceName: "Wowhead Classic",
    sourceUrl: `https://www.wowhead.com/classic/zone=${classicMap.mapId}/${classicMap.slug}`,
    src: `https://wow.zamimg.com/images/wow/classic/maps/enus/original/${classicMap.mapId}.jpg`,
  };
};
