const DUNGEON_MISSION_DEFINITIONS = [
  {
    id: 5,
    name: "The Deadmines",
    level: 17,
    minLevel: 10,
    durationReference: "1h30",
    durationFallback: 120,
    recommended: "18 - 23",
    gold: 15,
    rewardQualities: [2, 3],
    dungeonLootTable: {
      boss: [
        { quality: 2, chance: 80 },
        { quality: 3, chance: 20 },
      ],
      endboss: [
        { quality: 3, chance: 80 },
        { quality: 2, chance: 20 },
      ],
    },
    dungeonBosses: ["Sneed's Shredder", "Gilnid", "Mr. Smite", "Edwin VanCleef"],
    elite: true,
  },
  {
    id: 6,
    name: "Wailing Caverns",
    level: 18,
    minLevel: 10,
    durationOverrideSeconds: 115,
    durationReference: "1h45",
    durationFallback: 150,
    recommended: "15 - 25",
    gold: 15,
    rewardQualities: [2, 3],
    dungeonLootTable: {
      boss: [
        { quality: 2, chance: 80 },
        { quality: 3, chance: 20 },
      ],
      endboss: [
        { quality: 3, chance: 80 },
        { quality: 2, chance: 20 },
      ],
    },
    dungeonBosses: [
      "Kresh",
      "Lady Andacondra",
      "Lord Cobrahn",
      "Lord Pythas",
      "Lord Serpentis",
    ],
    elite: true,
  },
  {
    id: 7,
    name: "Shadowfang Keep",
    level: 22,
    minLevel: 15,
    durationReference: "0h50",
    durationFallback: 200,
    recommended: "22 - 30",
    gold: 18,
    rewardQualities: [2, 3],
    dungeonLootTable: {
      boss: [
        { quality: 3, chance: 80 },
        { quality: 2, chance: 20 },
      ],
      endboss: [{ quality: 3, chance: 100 }],
    },
    dungeonBosses: [
      "Commander Springvale",
      "Fenrus",
      "Wolf Master Nandos",
      "Archmage Arugal",
    ],
    elite: true,
  },
  {
    id: 22,
    name: "Blackfathom Deeps",
    level: 24,
    minLevel: 18,
    durationReference: "1h45",
    durationFallback: 220,
    recommended: "24 - 32",
    gold: 22,
    rewardQualities: [2, 3],
    dungeonLootTable: {
      boss: [
        { quality: 3, chance: 80 },
        { quality: 2, chance: 20 },
      ],
      endboss: [{ quality: 3, chance: 100 }],
    },
    dungeonBosses: [
      "Ghamoo-Ra",
      "Lady Sarevess",
      "Twilight Lord Kelris",
      "Aku'mai",
    ],
    elite: true,
  },
  {
    id: 23,
    name: "Gnomeregan",
    level: 29,
    minLevel: 19,
    durationReference: "1h45",
    durationFallback: 240,
    recommended: "29 - 34",
    gold: 24,
    rewardQualities: [2, 3],
    dungeonBosses: [
      "Grubbis",
      "Viscous Fallout",
      "Electrocutioner 6000",
      "Crowd Pummeler",
      "Mekgineer Thermaplugg",
    ],
    dungeonLootTable: {
      steps: [
        [{ quality: 2, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [
          { quality: 2, chance: 50 },
          { quality: 3, chance: 50 },
        ],
        [
          { quality: 2, chance: 50 },
          { quality: 3, chance: 50 },
        ],
        [{ quality: 3, chance: 100 }],
      ],
    },
    elite: true,
  },
  {
    id: 24,
    name: "Razorfen Kraul",
    level: 30,
    minLevel: 25,
    durationReference: "1h30",
    durationFallback: 260,
    recommended: "30 - 40",
    gold: 28,
    rewardQualities: [2, 3],
    dungeonLootTable: {
      boss: [
        { quality: 2, chance: 50 },
        { quality: 3, chance: 50 },
      ],
      endboss: [{ quality: 3, chance: 100 }],
    },
    dungeonBosses: [
      "Roogug",
      "Jargba",
      "Overlord Ramtusk",
      "Agathelos",
      "Earthcaller Halmgar",
      "Charlga Razorflank",
    ],
    elite: true,
  },
  {
    id: 40,
    name: "Scarlet Monastery: Graveyard",
    level: 31,
    minLevel: 20,
    entryLevel: 20,
    dungeonSetId: "scarlet_monastery",
    dungeonSetName: "Scarlet Monastery",
    dungeonWing: "Graveyard",
    wingOrder: 1,
    useDungeonSetLoot: true,
    keyId: "scarlet_monastery_key",
    requiresKey: false,
    durationReference: "0h40",
    durationFallback: 80,
    recommended: "26 - 36",
    gold: 25,
    rewardQualities: [2, 3],
    maxAttempts: 2,
    dungeonBosses: ["Interrogator Vishas", "Bloodmage Thalnos"],
    bonusDrops: [
      {
        chance: 0.01,
        qualityPriority: [4],
        includeWorldDrops: true,
        dungeonOnly: false,
        worldOnly: true,
        onComplete: true,
      },
    ],
    dungeonLootTable: {
      steps: [
        [
          { quality: 2, chance: 80 },
          { quality: 3, chance: 20 },
        ],
        [{ quality: 3, chance: 100 }],
      ],
    },
    elite: true,
  },
  {
    id: 41,
    name: "Scarlet Monastery: Library",
    level: 34,
    minLevel: 20,
    entryLevel: 20,
    dungeonSetId: "scarlet_monastery",
    dungeonSetName: "Scarlet Monastery",
    dungeonWing: "Library",
    wingOrder: 2,
    useDungeonSetLoot: true,
    keyId: "scarlet_monastery_key",
    requiresKey: false,
    durationReference: "0h50",
    durationFallback: 90,
    recommended: "29 - 39",
    gold: 28,
    rewardQualities: [2, 3],
    maxAttempts: 2,
    rewardKeys: ["scarlet_monastery_key"],
    dungeonBosses: ["Houndmaster Loksey", "Arcanist Doan"],
    bonusDrops: [
      {
        chance: 0.01,
        qualityPriority: [4],
        includeWorldDrops: true,
        dungeonOnly: false,
        worldOnly: true,
        onComplete: true,
      },
    ],
    dungeonLootTable: {
      steps: [
        [{ quality: 2, chance: 100 }],
        [
          { quality: 2, chance: 20 },
          { quality: 3, chance: 80 },
        ],
      ],
    },
    elite: true,
  },
  {
    id: 42,
    name: "Scarlet Monastery: Armory",
    level: 37,
    minLevel: 20,
    entryLevel: 20,
    dungeonSetId: "scarlet_monastery",
    dungeonSetName: "Scarlet Monastery",
    dungeonWing: "Armory",
    wingOrder: 3,
    useDungeonSetLoot: true,
    keyId: "scarlet_monastery_key",
    requiresKey: true,
    durationReference: "0h55",
    durationFallback: 100,
    recommended: "32 - 42",
    gold: 31,
    rewardQualities: [3],
    maxAttempts: 2,
    dungeonBosses: ["Herod"],
    bonusDrops: [
      {
        chance: 0.01,
        qualityPriority: [4],
        includeWorldDrops: true,
        dungeonOnly: false,
        worldOnly: true,
        onComplete: true,
      },
    ],
    dungeonLootTable: {
      steps: [[{ quality: 3, chance: 100 }]],
    },
    elite: true,
  },
  {
    id: 43,
    name: "Scarlet Monastery: Cathedral",
    level: 40,
    minLevel: 20,
    entryLevel: 20,
    dungeonSetId: "scarlet_monastery",
    dungeonSetName: "Scarlet Monastery",
    dungeonWing: "Cathedral",
    wingOrder: 4,
    useDungeonSetLoot: true,
    keyId: "scarlet_monastery_key",
    requiresKey: true,
    durationReference: "1h05",
    durationFallback: 110,
    recommended: "35 - 45",
    gold: 34,
    rewardQualities: [2, 3],
    maxAttempts: 2,
    dungeonBosses: [
      "High Inquisitor Fairbanks",
      "Scarlet Commander Mograine",
      "High Inquisitor Whitemane",
    ],
    bonusDrops: [
      {
        chance: 0.01,
        qualityPriority: [4],
        includeWorldDrops: true,
        dungeonOnly: false,
        worldOnly: true,
        onComplete: true,
      },
    ],
    dungeonLootTable: {
      steps: [
        [{ quality: 2, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
      ],
    },
    elite: true,
  },
  {
    id: 39,
    name: "Razorfen Downs",
    level: 37,
    minLevel: 28,
    durationReference: "1h30",
    durationFallback: 280,
    recommended: "37 - 47",
    gold: 32,
    rewardQualities: [2, 3],
    dungeonBosses: [
      "Tuten'kash",
      "Mordresh Fire Eye",
      "Glutton",
      "Amnennar The Coldbringer",
    ],
    dungeonLootTable: {
      steps: [
        [
          { quality: 2, chance: 80 },
          { quality: 3, chance: 20 },
        ],
        [
          { quality: 2, chance: 20 },
          { quality: 3, chance: 80 },
        ],
        [
          { quality: 2, chance: 20 },
          { quality: 3, chance: 80 },
        ],
        [{ quality: 3, chance: 100 }],
      ],
    },
    elite: true,
  },
  {
    id: 44,
    name: "Uldaman",
    level: 42,
    minLevel: 30,
    durationReference: "1h45",
    durationFallback: 300,
    recommended: "40 - 45",
    gold: 36,
    rewardQualities: [2, 3],
    dungeonBosses: [
      "Revelosh",
      "Ironaya",
      "Ancient Stone Keeper",
      "Grimlok",
      "Archaedas",
    ],
    dungeonLootTable: {
      steps: [
        [{ quality: 2, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [
          { quality: 2, chance: 50 },
          { quality: 3, chance: 50 },
        ],
        [
          { quality: 2, chance: 40 },
          { quality: 3, chance: 60 },
        ],
        [{ quality: 3, chance: 100 }],
      ],
    },
    elite: true,
  },
  {
    id: 45,
    name: "Zul'Farrak",
    level: 49,
    minLevel: 39,
    durationReference: "1h30",
    durationFallback: 320,
    recommended: "44 - 54",
    gold: 40,
    rewardQualities: [3],
    dungeonBosses: [
      "Antu'sul",
      "Witch Doctor Zum'rah",
      "Nekrum & Sezz'ziz",
      "Chief Ukorz Sandscalp",
      "Gahz'rilla",
    ],
    bonusDrops: [
      {
        chance: 0.01,
        qualityPriority: [4],
        includeWorldDrops: true,
        dungeonOnly: false,
        worldOnly: true,
        onComplete: true,
      },
    ],
    dungeonLootTable: {
      steps: [
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
      ],
    },
    elite: true,
  },
  {
    id: 46,
    name: "Maraudon",
    level: 48,
    minLevel: 40,
    durationReference: "3h00",
    durationFallback: 300,
    recommended: "45 - 52",
    gold: 44,
    rewardQualities: [3, 4],
    dungeonBosses: [
      "Lord Vyletongue",
      "Noxxion",
      "Razorlash",
      "Celebras",
      "Landslide",
      "Princess Theradras",
    ],
    dungeonLootTable: {
      steps: [
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [
          { quality: 2, chance: 50 },
          { quality: 3, chance: 50 },
        ],
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        {
          weights: [
            { quality: 4, chance: 5 },
            { quality: 3, chance: 95 },
          ],
          source: "mixed",
          includeWorldDrops: true,
          dungeonOnly: false,
          worldOnly: false,
        },
      ],
    },
    elite: true,
  },
  {
    id: 47,
    name: "Temple of Atal'Hakkar",
    level: 55,
    minLevel: 45,
    durationOverrideSeconds: 120,
    durationReference: "2h30",
    durationFallback: 230,
    recommended: "51 - 60",
    gold: 50,
    rewardQualities: [2, 3, 4],
    dungeonBosses: [
      "Atal'alarion",
      "Jammal'an & Ogom",
      "Weaver and Dreamscythe",
      "Hazzas & Morphaz",
      "Eranikus",
      "Avatar of Hakkar",
    ],
    dungeonLootTable: {
      steps: [
        [{ quality: 3, chance: 100 }],
        [
          { quality: 2, chance: 50 },
          { quality: 3, chance: 50 },
        ],
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        {
          weights: [
            { quality: 3, chance: 95 },
            { quality: 4, chance: 5 },
          ],
          source: "dungeon",
          includeWorldDrops: false,
          dungeonOnly: true,
          worldOnly: false,
        },
      ],
    },
    elite: true,
  },
  {
    id: 51,
    name: "Scholomance",
    level: 57,
    minLevel: 50,
    keyId: "scholomance_key",
    requiresKey: true,
    durationOverrideSeconds: 120,
    durationReference: "2h00",
    durationFallback: 120,
    recommended: "55 - 60",
    gold: 58,
    rewardQualities: [3],
    dungeonBosses: [
      "Jandice Barov",
      "Rattlegore",
      "Marduk Blackpool",
      "Vectus",
      "Ras Frostwhisper",
      "Lord Alexei Barov",
    ],
    bonusDrops: [
      {
        chance: 0.01,
        qualityPriority: [4],
        includeWorldDrops: true,
        dungeonOnly: false,
        worldOnly: true,
        onComplete: true,
      },
    ],
    dungeonLootTable: {
      steps: [
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
      ],
    },
    elite: true,
  },
  {
    id: 52,
    name: "Blackrock Spire",
    level: 58,
    minLevel: 55,
    entryLevel: 55,
    requiredPartySize: 5,
    durationOverrideSeconds: 105,
    durationReference: "1h45",
    durationFallback: 105,
    recommended: "57 - 60",
    dungeonSetId: "blackrock_spire",
    dungeonSetName: "Blackrock Spire",
    dungeonWing: "Lower Blackrock Spire",
    wingOrder: 1,
    useDungeonSetLoot: true,
    requiresKey: false,
    rewardKeys: ["seal_of_ascension"],
    gold: 68,
    baseFailChance: 30,
    rewardQualities: [3],
    dungeonBosses: [
      "Highlord Omokk",
      "Shadow Hunter Vosh'gajin",
      "War Master Voone",
      "Mother Smolderweb",
      "Urok Doomhowl",
      "Quartermaster Zigris",
      "Halycon",
      "Gizrul the Slavener",
      "Overlord Wyrmthalak",
    ],
    bonusDrops: [
      {
        chance: 0.01,
        qualityPriority: [4],
        includeWorldDrops: true,
        dungeonOnly: false,
        worldOnly: true,
        onComplete: true,
      },
    ],
    dungeonLootTable: {
      steps: [
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
      ],
    },
    elite: true,
  },
  {
    id: 53,
    name: "Blackrock Spire",
    level: 60,
    minLevel: 55,
    entryLevel: 55,
    requiredPartySize: 10,
    durationOverrideSeconds: 120,
    durationReference: "2h00",
    durationFallback: 120,
    recommended: "58 - 60",
    dungeonSetId: "blackrock_spire",
    dungeonSetName: "Blackrock Spire",
    dungeonWing: "Upper Blackrock Spire",
    wingOrder: 2,
    useDungeonSetLoot: true,
    keyId: "seal_of_ascension",
    requiresKey: true,
    requiresKeyForAllMembers: false,
    gold: 82,
    baseFailChance: 30,
    rewardQualities: [3, 4],
    dungeonBosses: [
      "Pyroguard Emberseer",
      "Solakar Flamewreath",
      "Goraluk Anvilcrack",
      "Jed Runewatcher",
      "Gyth",
      "Warchief Rend Blackhand",
      "The Beast",
      "General Drakkisath",
    ],
    bonusDrops: [
      {
        chance: 0.01,
        qualityPriority: [4],
        includeWorldDrops: true,
        dungeonOnly: false,
        worldOnly: true,
        onComplete: true,
      },
    ],
    dungeonLootTable: {
      steps: [
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [
          { quality: 3, chance: 97 },
          { quality: 4, chance: 3 },
        ],
        [{ quality: 3, chance: 100 }],
        [
          { quality: 3, chance: 97 },
          { quality: 4, chance: 3 },
        ],
      ],
    },
    elite: true,
  },
  {
    id: 60,
    name: "Stratholme Scarlet Side",
    level: 57,
    minLevel: 50,
    entryLevel: 50,
    durationOverrideSeconds: 90,
    dungeonSetId: "stratholme",
    dungeonSetName: "Stratholme",
    dungeonWing: "Scarlet Side",
    wingOrder: 1,
    useDungeonSetLoot: true,
    keyId: "key_to_the_city",
    requiresKey: false,
    rewardKeys: ["key_to_the_city"],
    durationReference: "1h30",
    durationFallback: 90,
    recommended: "55 - 60",
    gold: 62,
    rewardQualities: [3],
    dungeonBosses: [
      "Ezra Grimm",
      "The Unforgiven",
      "Timmy the Cruel",
      "Cannon Master Willey",
      "Archivist Galford",
      "Balnazzar",
    ],
    bonusDrops: [
      {
        chance: 0.01,
        qualityPriority: [4],
        includeWorldDrops: true,
        dungeonOnly: false,
        worldOnly: true,
        onComplete: true,
      },
    ],
    dungeonLootTable: {
      steps: [
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
      ],
    },
    elite: true,
  },
  {
    id: 61,
    name: "Stratholme Undead Side",
    level: 58,
    minLevel: 50,
    entryLevel: 50,
    durationOverrideSeconds: 100,
    dungeonSetId: "stratholme",
    dungeonSetName: "Stratholme",
    dungeonWing: "Undead Side",
    wingOrder: 2,
    useDungeonSetLoot: true,
    keyId: "key_to_the_city",
    requiresKey: true,
    durationReference: "1h40",
    durationFallback: 100,
    recommended: "55 - 60",
    gold: 64,
    rewardQualities: [2, 3],
    dungeonBosses: [
      "Magistrate Barthilas",
      "Nerub'enkan",
      "Baroness Anastari",
      "Maleki the Pallid",
      "Ramstein the Gorger",
      "Baron Rivendare",
    ],
    dungeonLootTable: {
      steps: [
        [{ quality: 3, chance: 100 }],
        [
          { quality: 2, chance: 50 },
          { quality: 3, chance: 50 },
        ],
        [
          { quality: 2, chance: 50 },
          { quality: 3, chance: 50 },
        ],
        [
          { quality: 2, chance: 50 },
          { quality: 3, chance: 50 },
        ],
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
      ],
    },
    elite: true,
  },
  {
    id: 62,
    name: "Molten Core",
    level: 60,
    minLevel: 56,
    entryLevel: 56,
    keyId: "molten_core_attunement",
    requiresKey: true,
    requiresKeyForAllMembers: true,
    durationOverrideSeconds: 180,
    durationReference: "3h00",
    durationFallback: 180,
    recommended: "58 - 60",
    dungeonSetId: "molten_core",
    dungeonSetName: "Molten Core",
    raidReset: {
      type: "weekly",
      weekday: 2,
    },
    gold: 120,
    baseFailChance: 45,
    rewardQualities: [4, 5],
    isRaid: true,
    minPartySize: 5,
    requiredPartySize: 40,
    raidMaxAttempts: 10,
    raidRoleRequirement: {
      Tank: 4,
      Healer: 8,
      DPS: 18,
      bonus: 20,
    },
    bossDropCountMin: 2,
    bossDropCountMax: 4,
    dungeonBosses: [
      "Lucifron",
      "Magmadar",
      "Gehennas",
      "Garr",
      "Baron Geddon",
      "Shazzrah",
      "Golemagg",
      "Sulfuron",
      "Majordomo Executus",
      "Ragnaros",
    ],
    bonusDrops: [
      {
        chance: 0.02,
        qualityPriority: [4],
        includeWorldDrops: true,
        dungeonOnly: false,
        worldOnly: true,
      },
    ],
    dungeonLootTable: {
      steps: [
        [{ quality: 4, chance: 100 }],
        [{ quality: 4, chance: 100 }],
        [{ quality: 4, chance: 100 }],
        [{ quality: 4, chance: 100 }],
        [{ quality: 4, chance: 100 }],
        [{ quality: 4, chance: 100 }],
        [{ quality: 4, chance: 100 }],
        [{ quality: 4, chance: 100 }],
        [{ quality: 4, chance: 100 }],
        [
          { quality: 4, chance: 99 },
          { quality: 5, chance: 1 },
        ],
      ],
    },
    elite: true,
  },
  {
    id: 63,
    name: "Zul'Gurub",
    level: 60,
    minLevel: 58,
    entryLevel: 58,
    durationOverrideSeconds: 150,
    durationReference: "2h30",
    durationFallback: 150,
    recommended: "58 - 60",
    dungeonSetId: "zul_gurub",
    dungeonSetName: "Zul'Gurub",
    raidReset: {
      type: "interval",
      intervalDays: 3,
      anchorDayIndex: 0,
    },
    gold: 90,
    baseFailChance: 38,
    rewardQualities: [4],
    isRaid: true,
    minPartySize: 5,
    requiredPartySize: 20,
    raidMaxAttempts: 8,
    raidRoleRequirement: {
      Tank: 2,
      Healer: 5,
      DPS: 13,
      bonus: 18,
    },
    bossDropCountMin: 1,
    bossDropCountMax: 2,
    dungeonBosses: [
      "High Priest Venoxis",
      "High Priestess Jeklik",
      "High Priestess Mar'li",
      "High Priest Thekal",
      "High Priestess Arlokk",
      "Bloodlord Mandokir",
      "Gahz'ranka",
      "Jin'do the Hexxer",
      "Hakkar",
    ],
    bonusDrops: [
      {
        chance: 0.01,
        qualityPriority: [4],
        includeWorldDrops: true,
        dungeonOnly: false,
        worldOnly: true,
      },
    ],
    dungeonLootTable: {
      steps: [
        [{ quality: 4, chance: 100 }],
        [{ quality: 4, chance: 100 }],
        [{ quality: 4, chance: 100 }],
        [{ quality: 4, chance: 100 }],
        [{ quality: 4, chance: 100 }],
        [{ quality: 4, chance: 100 }],
        [{ quality: 4, chance: 100 }],
        [{ quality: 4, chance: 100 }],
        [{ quality: 4, chance: 100 }],
      ],
    },
    elite: true,
  },
  {
    id: 64,
    name: "Ruins of Ahn'Qiraj",
    level: 60,
    minLevel: 58,
    entryLevel: 58,
    durationOverrideSeconds: 145,
    durationReference: "2h25",
    durationFallback: 145,
    recommended: "58 - 60",
    dungeonSetId: "ahn_qiraj_ruins",
    dungeonSetName: "Ruins of Ahn'Qiraj",
    raidReset: {
      type: "interval",
      intervalDays: 3,
      anchorDayIndex: 0,
    },
    gold: 95,
    baseFailChance: 40,
    rewardQualities: [4],
    isRaid: true,
    requiresKey: false,
    minPartySize: 5,
    requiredPartySize: 20,
    raidMaxAttempts: 8,
    raidRoleRequirement: {
      Tank: 2,
      Healer: 5,
      DPS: 13,
      bonus: 18,
    },
    bossDropCountMin: 1,
    bossDropCountMax: 2,
    dungeonBosses: [
      "Kurinnaxx",
      "General Rajaxx",
      "Buru the Gorger",
      "Moam",
      "Ayamiss the Hunter",
      "Ossirian the Unscarred",
    ],
    bonusDrops: [
      {
        chance: 0.01,
        qualityPriority: [4],
        includeWorldDrops: true,
        dungeonOnly: false,
        worldOnly: true,
      },
    ],
    dungeonLootTable: {
      steps: [
        [{ quality: 4, chance: 100 }],
        [{ quality: 4, chance: 100 }],
        [{ quality: 4, chance: 100 }],
        [{ quality: 4, chance: 100 }],
        [{ quality: 4, chance: 100 }],
        [{ quality: 4, chance: 100 }],
      ],
    },
    elite: true,
  },
  {
    id: 65,
    name: "Temple of Ahn'Qiraj",
    level: 60,
    minLevel: 60,
    entryLevel: 60,
    durationOverrideSeconds: 210,
    durationReference: "3h30",
    durationFallback: 210,
    recommended: "60",
    dungeonSetId: "ahn_qiraj_temple",
    dungeonSetName: "Temple of Ahn'Qiraj",
    raidReset: {
      type: "weekly",
      weekday: 2,
    },
    gold: 140,
    baseFailChance: 48,
    rewardQualities: [4, 5],
    isRaid: true,
    requiresKey: false,
    minPartySize: 5,
    requiredPartySize: 40,
    raidMaxAttempts: 10,
    raidRoleRequirement: {
      Tank: 4,
      Healer: 8,
      DPS: 18,
      bonus: 20,
    },
    bossDropCountMin: 2,
    bossDropCountMax: 4,
    dungeonBosses: [
      "The Prophet Skeram",
      "Bug Trio",
      "Battleguard Sartura",
      "Fankriss the Unyielding",
      "Viscidus",
      "Princess Huhuran",
      "Twin Emperors",
      "Ouro",
      "C'Thun",
    ],
    bonusDrops: [
      {
        chance: 0.02,
        qualityPriority: [4],
        includeWorldDrops: true,
        dungeonOnly: false,
        worldOnly: true,
      },
    ],
    dungeonLootTable: {
      steps: [
        [{ quality: 4, chance: 100 }],
        [{ quality: 4, chance: 100 }],
        [{ quality: 4, chance: 100 }],
        [{ quality: 4, chance: 100 }],
        [{ quality: 4, chance: 100 }],
        [{ quality: 4, chance: 100 }],
        [{ quality: 4, chance: 100 }],
        [{ quality: 4, chance: 100 }],
        [
          { quality: 4, chance: 97 },
          { quality: 5, chance: 3 },
        ],
      ],
    },
    elite: true,
  },
  {
    id: 48,
    name: "BRD: Arena & Prison",
    level: 50,
    minLevel: 42,
    entryLevel: 42,
    durationOverrideSeconds: 60,
    dungeonSetId: "blackrock_depths",
    dungeonSetName: "Blackrock Depths",
    dungeonWing: "Arena & Prison",
    wingOrder: 1,
    useDungeonSetLoot: true,
    keyId: "shadowforge_key",
    requiresKey: false,
    rewardKeys: ["shadowforge_key"],
    durationReference: "1h00",
    durationFallback: 100,
    recommended: "50 - 56",
    gold: 52,
    rewardQualities: [3, 4],
    dungeonBosses: [
      "Interrogator Gerstahn",
      "Lord Roccor",
      "Houndmaster Grebmar",
      "Gorosh the Dervish",
    ],
    bonusDrops: [
      {
        chance: 0.01,
        qualityPriority: [4],
        includeWorldDrops: true,
        dungeonOnly: false,
        worldOnly: true,
        onComplete: true,
      },
    ],
    dungeonLootTable: {
      steps: [
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [
          { quality: 3, chance: 90 },
          { quality: 4, chance: 10 },
        ],
      ],
    },
    elite: true,
  },
  {
    id: 49,
    name: "BRD: Shadowforge",
    level: 52,
    minLevel: 42,
    entryLevel: 42,
    durationOverrideSeconds: 60,
    dungeonSetId: "blackrock_depths",
    dungeonSetName: "Blackrock Depths",
    dungeonWing: "Shadowforge",
    wingOrder: 2,
    useDungeonSetLoot: true,
    keyId: "shadowforge_key",
    requiresKey: true,
    durationReference: "1h00",
    durationFallback: 100,
    recommended: "52 - 58",
    gold: 55,
    rewardQualities: [3],
    dungeonBosses: [
      "Fineous Darkvire",
      "Pyromancer Loregrain",
      "Bael'gar",
      "Lord Incendius",
    ],
    bonusDrops: [
      {
        chance: 0.01,
        qualityPriority: [4],
        includeWorldDrops: true,
        dungeonOnly: false,
        worldOnly: true,
        onComplete: true,
      },
    ],
    dungeonLootTable: {
      steps: [
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
      ],
    },
    elite: true,
  },
  {
    id: 50,
    name: "BRD: Shadowforge City",
    level: 55,
    minLevel: 42,
    entryLevel: 42,
    durationOverrideSeconds: 60,
    dungeonSetId: "blackrock_depths",
    dungeonSetName: "Blackrock Depths",
    dungeonWing: "Shadowforge City",
    wingOrder: 3,
    useDungeonSetLoot: true,
    keyId: "shadowforge_key",
    requiresKey: true,
    rewardKeys: ["molten_core_attunement"],
    durationReference: "1h00",
    durationFallback: 100,
    recommended: "55 - 60",
    gold: 60,
    rewardQualities: [3, 4],
    dungeonBosses: [
      "General Angerforge",
      "Golem Lord Argelmach",
      "The Grim Guzzler",
      "Ambassador Flamelash",
      "Magmus",
      "Emperor Dagran Thaurissan",
    ],
    bonusDrops: [
      {
        chance: 0.01,
        qualityPriority: [4],
        includeWorldDrops: true,
        dungeonOnly: false,
        worldOnly: true,
        onComplete: true,
      },
    ],
    dungeonLootTable: {
      steps: [
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [
          { quality: 3, chance: 90 },
          { quality: 4, chance: 10 },
        ],
      ],
    },
    elite: true,
  },
];

const cloneDungeonLootTable = (lootTable) =>
  lootTable ? JSON.parse(JSON.stringify(lootTable)) : lootTable;
const cloneBonusDrops = (bonusDrops) =>
  Array.isArray(bonusDrops) ? JSON.parse(JSON.stringify(bonusDrops)) : bonusDrops;

export const buildDungeonMissions = ({
  getDungeonDurationFromReference,
  getDungeonMissionExp,
}) =>
  DUNGEON_MISSION_DEFINITIONS.map((mission) => {
    const duration =
      Number.isFinite(mission.durationOverrideSeconds) &&
      mission.durationOverrideSeconds > 0
        ? Math.floor(mission.durationOverrideSeconds)
        : getDungeonDurationFromReference(
            mission.durationReference,
            mission.durationFallback,
          );
    return {
      id: mission.id,
      type: "dungeon",
      typeLabel: "Dungeon",
      name: mission.name,
      level: mission.level,
      minLevel: mission.minLevel,
      duration,
      exp: getDungeonMissionExp(mission.recommended, mission.level, duration),
      gold: mission.gold,
      baseFailChance: Number.isFinite(mission.baseFailChance)
        ? mission.baseFailChance
        : undefined,
      rewardQualities: Array.isArray(mission.rewardQualities)
        ? [...mission.rewardQualities]
        : [],
      maxAttempts: Number.isFinite(mission.maxAttempts)
        ? Math.max(1, Math.floor(mission.maxAttempts))
        : undefined,
      rewardKeys: Array.isArray(mission.rewardKeys) ? [...mission.rewardKeys] : [],
      dungeonLootTable: cloneDungeonLootTable(mission.dungeonLootTable),
      bonusDrops: cloneBonusDrops(mission.bonusDrops),
      dungeonBosses: Array.isArray(mission.dungeonBosses)
        ? [...mission.dungeonBosses]
        : undefined,
      dungeonSetId: mission.dungeonSetId,
      dungeonSetName: mission.dungeonSetName,
      dungeonWing: mission.dungeonWing,
      wingOrder: mission.wingOrder,
      entryLevel: mission.entryLevel,
      useDungeonSetLoot: mission.useDungeonSetLoot,
      keyId: mission.keyId,
      requiresKey: mission.requiresKey,
      requiresKeyForAllMembers: mission.requiresKeyForAllMembers === true,
      isRaid: mission.isRaid === true,
      requiredPartySize: Number.isFinite(mission.requiredPartySize)
        ? Math.max(1, Math.floor(mission.requiredPartySize))
        : undefined,
      minPartySize: Number.isFinite(mission.minPartySize)
        ? Math.max(1, Math.floor(mission.minPartySize))
        : undefined,
      raidMaxAttempts: Number.isFinite(mission.raidMaxAttempts)
        ? Math.max(1, Math.floor(mission.raidMaxAttempts))
        : undefined,
      raidRoleRequirement:
        mission.raidRoleRequirement &&
        typeof mission.raidRoleRequirement === "object"
          ? { ...mission.raidRoleRequirement }
          : undefined,
      raidReset:
        mission.raidReset && typeof mission.raidReset === "object"
          ? { ...mission.raidReset }
          : undefined,
      bossDropCountMin: Number.isFinite(mission.bossDropCountMin)
        ? mission.bossDropCountMin
        : undefined,
      bossDropCountMax: Number.isFinite(mission.bossDropCountMax)
        ? mission.bossDropCountMax
        : undefined,
      endbossDropCountMin: Number.isFinite(mission.endbossDropCountMin)
        ? mission.endbossDropCountMin
        : undefined,
      endbossDropCountMax: Number.isFinite(mission.endbossDropCountMax)
        ? mission.endbossDropCountMax
        : undefined,
      elite: mission.elite === true,
      recommended: mission.recommended,
    };
  });
