const DUNGEON_MISSION_DEFINITIONS = [
  {
    id: 5,
    name: "The Deadmines",
    level: 17,
    minLevel: 10,
    durationReference: "1h30",
    durationFallback: 120,
    recommended: "18 - 23",
    gold: 15,
    rewardQualities: [2, 3],
    dungeonLootTable: {
      boss: [
        { quality: 2, chance: 80 },
        { quality: 3, chance: 20 },
      ],
      endboss: [
        { quality: 3, chance: 80 },
        { quality: 2, chance: 20 },
      ],
    },
    dungeonBosses: ["Sneed's Shredder", "Gilnid", "Mr. Smite", "Edwin VanCleef"],
    elite: true,
  },
  {
    id: 6,
    name: "Wailing Caverns",
    level: 18,
    minLevel: 10,
    durationReference: "1h45",
    durationFallback: 150,
    recommended: "15 - 25",
    gold: 15,
    rewardQualities: [2, 3],
    dungeonLootTable: {
      boss: [
        { quality: 2, chance: 80 },
        { quality: 3, chance: 20 },
      ],
      endboss: [
        { quality: 3, chance: 80 },
        { quality: 2, chance: 20 },
      ],
    },
    dungeonBosses: [
      "Kresh",
      "Lady Andacondra",
      "Lord Cobrahn",
      "Lord Pythas",
      "Lord Serpentis",
    ],
    elite: true,
  },
  {
    id: 7,
    name: "Shadowfang Keep",
    level: 22,
    minLevel: 15,
    durationReference: "0h50",
    durationFallback: 200,
    recommended: "22 - 30",
    gold: 18,
    rewardQualities: [2, 3],
    dungeonLootTable: {
      boss: [
        { quality: 3, chance: 80 },
        { quality: 2, chance: 20 },
      ],
      endboss: [{ quality: 3, chance: 100 }],
    },
    dungeonBosses: [
      "Commander Springvale",
      "Fenrus",
      "Wolf Master Nandos",
      "Archmage Arugal",
    ],
    elite: true,
  },
  {
    id: 22,
    name: "Blackfathom Deeps",
    level: 24,
    minLevel: 18,
    durationReference: "1h45",
    durationFallback: 220,
    recommended: "24 - 32",
    gold: 22,
    rewardQualities: [2, 3],
    dungeonLootTable: {
      boss: [
        { quality: 3, chance: 80 },
        { quality: 2, chance: 20 },
      ],
      endboss: [{ quality: 3, chance: 100 }],
    },
    dungeonBosses: [
      "Ghamoo-Ra",
      "Lady Sarevess",
      "Twilight Lord Kelris",
      "Aku'mai",
    ],
    elite: true,
  },
  {
    id: 23,
    name: "Gnomeregan",
    level: 29,
    minLevel: 19,
    durationReference: "1h45",
    durationFallback: 240,
    recommended: "29 - 34",
    gold: 24,
    rewardQualities: [2, 3],
    dungeonBosses: [
      "Grubbis",
      "Viscous Fallout",
      "Electrocutioner 6000",
      "Crowd Pummeler",
      "Mekgineer Thermaplugg",
    ],
    dungeonLootTable: {
      steps: [
        [{ quality: 2, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [
          { quality: 2, chance: 50 },
          { quality: 3, chance: 50 },
        ],
        [
          { quality: 2, chance: 50 },
          { quality: 3, chance: 50 },
        ],
        [{ quality: 3, chance: 100 }],
      ],
    },
    elite: true,
  },
  {
    id: 24,
    name: "Razorfen Kraul",
    level: 30,
    minLevel: 25,
    durationReference: "1h30",
    durationFallback: 260,
    recommended: "30 - 40",
    gold: 28,
    rewardQualities: [2, 3],
    dungeonLootTable: {
      boss: [
        { quality: 2, chance: 50 },
        { quality: 3, chance: 50 },
      ],
      endboss: [{ quality: 3, chance: 100 }],
    },
    elite: true,
  },
  {
    id: 40,
    name: "Scarlet Monastery: Graveyard",
    level: 31,
    minLevel: 20,
    entryLevel: 20,
    dungeonSetId: "scarlet_monastery",
    dungeonSetName: "Scarlet Monastery",
    dungeonWing: "Graveyard",
    wingOrder: 1,
    useDungeonSetLoot: true,
    keyId: "scarlet_monastery_key",
    requiresKey: false,
    durationReference: "0h40",
    durationFallback: 80,
    recommended: "26 - 36",
    gold: 25,
    rewardQualities: [2, 3],
    dungeonBosses: ["Interrogator Vishas", "Bloodmage Thalnos"],
    bonusDrops: [
      {
        chance: 0.01,
        qualityPriority: [4],
        includeWorldDrops: true,
        dungeonOnly: false,
        worldOnly: true,
        onComplete: true,
      },
    ],
    dungeonLootTable: {
      steps: [
        [
          { quality: 2, chance: 80 },
          { quality: 3, chance: 20 },
        ],
        [{ quality: 3, chance: 100 }],
      ],
    },
    elite: true,
  },
  {
    id: 41,
    name: "Scarlet Monastery: Library",
    level: 34,
    minLevel: 20,
    entryLevel: 20,
    dungeonSetId: "scarlet_monastery",
    dungeonSetName: "Scarlet Monastery",
    dungeonWing: "Library",
    wingOrder: 2,
    useDungeonSetLoot: true,
    keyId: "scarlet_monastery_key",
    requiresKey: false,
    durationReference: "0h50",
    durationFallback: 90,
    recommended: "29 - 39",
    gold: 28,
    rewardQualities: [2, 3],
    rewardKeys: ["scarlet_monastery_key"],
    dungeonBosses: ["Houndmaster Loksey", "Arcanist Doan"],
    bonusDrops: [
      {
        chance: 0.01,
        qualityPriority: [4],
        includeWorldDrops: true,
        dungeonOnly: false,
        worldOnly: true,
        onComplete: true,
      },
    ],
    dungeonLootTable: {
      steps: [
        [{ quality: 2, chance: 100 }],
        [
          { quality: 2, chance: 20 },
          { quality: 3, chance: 80 },
        ],
      ],
    },
    elite: true,
  },
  {
    id: 42,
    name: "Scarlet Monastery: Armory",
    level: 37,
    minLevel: 20,
    entryLevel: 20,
    dungeonSetId: "scarlet_monastery",
    dungeonSetName: "Scarlet Monastery",
    dungeonWing: "Armory",
    wingOrder: 3,
    useDungeonSetLoot: true,
    keyId: "scarlet_monastery_key",
    requiresKey: true,
    durationReference: "0h55",
    durationFallback: 100,
    recommended: "32 - 42",
    gold: 31,
    rewardQualities: [3],
    dungeonBosses: ["Herod"],
    bonusDrops: [
      {
        chance: 0.01,
        qualityPriority: [4],
        includeWorldDrops: true,
        dungeonOnly: false,
        worldOnly: true,
        onComplete: true,
      },
    ],
    dungeonLootTable: {
      steps: [[{ quality: 3, chance: 100 }]],
    },
    elite: true,
  },
  {
    id: 43,
    name: "Scarlet Monastery: Cathedral",
    level: 40,
    minLevel: 20,
    entryLevel: 20,
    dungeonSetId: "scarlet_monastery",
    dungeonSetName: "Scarlet Monastery",
    dungeonWing: "Cathedral",
    wingOrder: 4,
    useDungeonSetLoot: true,
    keyId: "scarlet_monastery_key",
    requiresKey: true,
    durationReference: "1h05",
    durationFallback: 110,
    recommended: "35 - 45",
    gold: 34,
    rewardQualities: [2, 3],
    dungeonBosses: [
      "High Inquisitor Fairbanks",
      "Scarlet Commander Mograine",
      "High Inquisitor Whitemane",
    ],
    bonusDrops: [
      {
        chance: 0.01,
        qualityPriority: [4],
        includeWorldDrops: true,
        dungeonOnly: false,
        worldOnly: true,
        onComplete: true,
      },
    ],
    dungeonLootTable: {
      steps: [
        [{ quality: 2, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
      ],
    },
    elite: true,
  },
  {
    id: 39,
    name: "Razorfen Downs",
    level: 37,
    minLevel: 28,
    durationReference: "1h30",
    durationFallback: 280,
    recommended: "37 - 47",
    gold: 32,
    rewardQualities: [2, 3],
    dungeonBosses: [
      "Tuten'kash",
      "Mordresh Fire Eye",
      "Glutton",
      "Amnennar The Coldbringer",
    ],
    dungeonLootTable: {
      steps: [
        [
          { quality: 2, chance: 80 },
          { quality: 3, chance: 20 },
        ],
        [
          { quality: 2, chance: 20 },
          { quality: 3, chance: 80 },
        ],
        [
          { quality: 2, chance: 20 },
          { quality: 3, chance: 80 },
        ],
        [{ quality: 3, chance: 100 }],
      ],
    },
    elite: true,
  },
  {
    id: 44,
    name: "Uldaman",
    level: 42,
    minLevel: 30,
    durationReference: "1h45",
    durationFallback: 300,
    recommended: "40 - 45",
    gold: 36,
    rewardQualities: [2, 3],
    dungeonBosses: [
      "Revelosh",
      "Ironaya",
      "Ancient Stone Keeper",
      "Grimlok",
      "Archaedas",
    ],
    dungeonLootTable: {
      steps: [
        [{ quality: 2, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [
          { quality: 2, chance: 50 },
          { quality: 3, chance: 50 },
        ],
        [
          { quality: 2, chance: 40 },
          { quality: 3, chance: 60 },
        ],
        [{ quality: 3, chance: 100 }],
      ],
    },
    elite: true,
  },
  {
    id: 45,
    name: "Zul'Farrak",
    level: 49,
    minLevel: 39,
    durationReference: "1h30",
    durationFallback: 320,
    recommended: "44 - 54",
    gold: 40,
    rewardQualities: [3],
    dungeonBosses: [
      "Antu'sul",
      "Witch Doctor Zum'rah",
      "Nekrum & Sezz'ziz",
      "Chief Ukorz Sandscalp",
      "Gahz'rilla",
    ],
    bonusDrops: [
      {
        chance: 0.01,
        qualityPriority: [4],
        includeWorldDrops: true,
        dungeonOnly: false,
        worldOnly: true,
        onComplete: true,
      },
    ],
    dungeonLootTable: {
      steps: [
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
      ],
    },
    elite: true,
  },
  {
    id: 46,
    name: "Maraudon",
    level: 48,
    minLevel: 40,
    durationReference: "3h00",
    durationFallback: 300,
    recommended: "45 - 52",
    gold: 44,
    rewardQualities: [3, 4],
    dungeonBosses: [
      "Lord Vyletongue",
      "Noxxion",
      "Razorlash",
      "Celebras",
      "Landslide",
      "Princess Theradras",
    ],
    dungeonLootTable: {
      steps: [
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [
          { quality: 2, chance: 50 },
          { quality: 3, chance: 50 },
        ],
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        {
          weights: [
            { quality: 4, chance: 5 },
            { quality: 3, chance: 95 },
          ],
          source: "mixed",
          includeWorldDrops: true,
          dungeonOnly: false,
          worldOnly: false,
        },
      ],
    },
    elite: true,
  },
  {
    id: 47,
    name: "Temple of Atal'Hakkar",
    level: 55,
    minLevel: 45,
    durationReference: "2h30",
    durationFallback: 230,
    recommended: "51 - 60",
    gold: 50,
    rewardQualities: [2, 3, 4],
    dungeonBosses: [
      "Atal'alarion",
      "Jammal'an & Ogom",
      "Weaver and Dreamscythe",
      "Hazzas & Morphaz",
      "Eranikus",
      "Avatar of Hakkar",
    ],
    dungeonLootTable: {
      steps: [
        [{ quality: 3, chance: 100 }],
        [
          { quality: 2, chance: 50 },
          { quality: 3, chance: 50 },
        ],
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        {
          weights: [
            { quality: 3, chance: 95 },
            { quality: 4, chance: 5 },
          ],
          source: "dungeon",
          includeWorldDrops: false,
          dungeonOnly: true,
          worldOnly: false,
        },
      ],
    },
    elite: true,
  },
];

const cloneDungeonLootTable = (lootTable) =>
  lootTable ? JSON.parse(JSON.stringify(lootTable)) : lootTable;
const cloneBonusDrops = (bonusDrops) =>
  Array.isArray(bonusDrops) ? JSON.parse(JSON.stringify(bonusDrops)) : bonusDrops;

export const buildDungeonMissions = ({
  getDungeonDurationFromReference,
  getDungeonMissionExp,
}) =>
  DUNGEON_MISSION_DEFINITIONS.map((mission) => {
    const duration = getDungeonDurationFromReference(
      mission.durationReference,
      mission.durationFallback,
    );
    return {
      id: mission.id,
      type: "dungeon",
      typeLabel: "Dungeon",
      name: mission.name,
      level: mission.level,
      minLevel: mission.minLevel,
      duration,
      exp: getDungeonMissionExp(mission.recommended, mission.level, duration),
      gold: mission.gold,
      rewardQualities: Array.isArray(mission.rewardQualities)
        ? [...mission.rewardQualities]
        : [],
      rewardKeys: Array.isArray(mission.rewardKeys) ? [...mission.rewardKeys] : [],
      dungeonLootTable: cloneDungeonLootTable(mission.dungeonLootTable),
      bonusDrops: cloneBonusDrops(mission.bonusDrops),
      dungeonBosses: Array.isArray(mission.dungeonBosses)
        ? [...mission.dungeonBosses]
        : undefined,
      dungeonSetId: mission.dungeonSetId,
      dungeonSetName: mission.dungeonSetName,
      dungeonWing: mission.dungeonWing,
      wingOrder: mission.wingOrder,
      entryLevel: mission.entryLevel,
      useDungeonSetLoot: mission.useDungeonSetLoot,
      keyId: mission.keyId,
      requiresKey: mission.requiresKey,
      elite: mission.elite === true,
      recommended: mission.recommended,
    };
  });
