export const CONFIG = {
  MAX_ROSTER: 10,
  GOLD_CAP: 1000,
  // Active progression phase for now. Raise this toward MAX_SUPPORTED_LEVEL over time.
  LEVEL_CAP: 25,
  MAX_SUPPORTED_LEVEL: 60,
  TICK_RATE: 1000,
  XP_TABLE: [
    0, 400, 900, 1400, 2100, 2800, 3600, 4500, 5400, 6500, 7600, 8700, 9800,
    11000, 12300, 13600, 15000, 16400, 17800, 19200, 20800,
  ],
};

const getQuestDuration = (level, elite = false) => {
  let baseDuration;
  if (level < 10) {
    // Early leveling stays fast: 8s - 15s
    baseDuration = Math.min(15, 8 + Math.max(0, level - 1));
  } else if (level < 20) {
    // Mid band: 15s - 20s
    baseDuration = Math.min(20, 15 + Math.floor((level - 10) / 2));
  } else {
    // High band: 20s - 30s
    baseDuration = Math.min(30, 20 + Math.floor((level - 20) * 1.5));
  }
  return elite ? baseDuration * 2 : baseDuration;
};

const getQuestRewardQualities = (level, elite = false) => {
  if (elite) return level >= 18 ? [3] : [2];
  return level >= 12 ? [2] : [1];
};

export const INITIAL_MISSIONS = [
  {
    id: 1,
    type: "quest",
    typeLabel: "Quest",
    name: "Clear Kobold Mine",
    level: 1,
    duration: getQuestDuration(1),
    exp: 450,
    gold: 1,
    rewardQualities: getQuestRewardQualities(1),
    elite: false,
  },
  {
    id: 2,
    type: "quest",
    typeLabel: "Quest",
    name: "Gather Herbs",
    level: 2,
    duration: getQuestDuration(2),
    exp: 600,
    gold: 2,
    rewardQualities: getQuestRewardQualities(2),
    elite: false,
  },
  {
    id: 3,
    type: "quest",
    typeLabel: "Quest",
    name: "Wolf Hunt",
    level: 5,
    duration: getQuestDuration(5),
    exp: 1200,
    gold: 4,
    rewardQualities: getQuestRewardQualities(5),
    elite: false,
  },
  {
    id: 4,
    type: "quest",
    typeLabel: "Elite Quest",
    name: "Elite: Defeat Hogger",
    level: 10,
    duration: getQuestDuration(10, true),
    exp: 4000,
    gold: 8,
    rewardQualities: getQuestRewardQualities(10, true),
    elite: true,
  },
  {
    id: 8,
    type: "quest",
    typeLabel: "Quest",
    name: "Secure the Westfall Roads",
    level: 8,
    duration: getQuestDuration(8),
    exp: 2200,
    gold: 5,
    rewardQualities: getQuestRewardQualities(8),
    elite: false,
  },
  {
    id: 9,
    type: "quest",
    typeLabel: "Quest",
    name: "Purge the Moonbrook Cellar",
    level: 12,
    duration: getQuestDuration(12),
    exp: 3600,
    gold: 6,
    rewardQualities: getQuestRewardQualities(12),
    elite: false,
  },
  {
    id: 10,
    type: "quest",
    typeLabel: "Quest",
    name: "Escort the Iron Caravan",
    level: 14,
    duration: getQuestDuration(14),
    exp: 4800,
    gold: 7,
    rewardQualities: getQuestRewardQualities(14),
    elite: false,
  },
  {
    id: 11,
    type: "quest",
    typeLabel: "Quest",
    name: "Recover Stolen Reagents",
    level: 16,
    duration: getQuestDuration(16),
    exp: 6200,
    gold: 8,
    rewardQualities: getQuestRewardQualities(16),
    elite: false,
  },
  {
    id: 12,
    type: "quest",
    typeLabel: "Quest",
    name: "Hunt the Darkfang Pack",
    level: 18,
    duration: getQuestDuration(18),
    exp: 7800,
    gold: 9,
    rewardQualities: getQuestRewardQualities(18),
    elite: false,
  },
  {
    id: 13,
    type: "quest",
    typeLabel: "Quest",
    name: "Defend Sentinel Hill",
    level: 21,
    duration: getQuestDuration(21),
    exp: 9800,
    gold: 11,
    rewardQualities: getQuestRewardQualities(21),
    elite: false,
  },
  {
    id: 14,
    type: "quest",
    typeLabel: "Quest",
    name: "Assault on Ravenclaw Camp",
    level: 24,
    duration: getQuestDuration(24),
    exp: 12500,
    gold: 13,
    rewardQualities: getQuestRewardQualities(24),
    elite: false,
  },
  {
    id: 15,
    type: "quest",
    typeLabel: "Elite Quest",
    name: "Elite: Break the Defias Siege",
    level: 14,
    duration: getQuestDuration(14, true),
    exp: 7600,
    gold: 12,
    rewardQualities: getQuestRewardQualities(14, true),
    elite: true,
  },
  {
    id: 16,
    type: "quest",
    typeLabel: "Elite Quest",
    name: "Elite: Slay the Nightbane Alpha",
    level: 18,
    duration: getQuestDuration(18, true),
    exp: 11000,
    gold: 15,
    rewardQualities: getQuestRewardQualities(18, true),
    elite: true,
  },
  {
    id: 17,
    type: "quest",
    typeLabel: "Elite Quest",
    name: "Elite: Hold the Bridge at Dawn",
    level: 21,
    duration: getQuestDuration(21, true),
    exp: 14500,
    gold: 18,
    rewardQualities: getQuestRewardQualities(21, true),
    elite: true,
  },
  {
    id: 18,
    type: "quest",
    typeLabel: "Elite Quest",
    name: "Elite: Purge the Shadow Altar",
    level: 24,
    duration: getQuestDuration(24, true),
    exp: 18000,
    gold: 21,
    rewardQualities: getQuestRewardQualities(24, true),
    elite: true,
  },
  {
    id: 5,
    type: "dungeon",
    typeLabel: "Dungeon",
    name: "The Deadmines",
    level: 17,
    minLevel: 10,
    duration: 120,
    exp: 17000,
    gold: 15,
    rewardQualities: [2, 3],
    elite: true,
    recommended: "18 - 23",
  },
  {
    id: 6,
    type: "dungeon",
    typeLabel: "Dungeon",
    name: "Wailing Caverns",
    level: 18,
    minLevel: 10,
    duration: 150,
    exp: 20000,
    gold: 15,
    rewardQualities: [2, 3],
    elite: true,
    recommended: "15 - 25",
  },
  {
    id: 7,
    type: "dungeon",
    typeLabel: "Dungeon",
    name: "Shadowfang Keep",
    level: 22,
    minLevel: 15,
    duration: 200,
    exp: 26000,
    gold: 18,
    rewardQualities: [2, 3],
    elite: true,
    recommended: "22 - 30",
  },
];

export const PROFESSIONS = Object.freeze({
  MINING: "Mining",
  HERBALISM: "Herbalism",
  SKINNING: "Skinning",
  BLACKSMITHING: "Blacksmithing",
  LEATHERWORKING: "Leatherworking",
  TAILORING: "Tailoring",
  ENCHANTING: "Enchanting",
  ALCHEMY: "Alchemy",
});

export const PROFESSIONS_LIST = Object.values(PROFESSIONS);

export const DEFAULT_PROF_PAIR = [
  PROFESSIONS.MINING,
  PROFESSIONS.HERBALISM,
];

export const PROF_PAIRS = {
  Warrior: [PROFESSIONS.MINING, PROFESSIONS.BLACKSMITHING],
  Paladin: [PROFESSIONS.MINING, PROFESSIONS.BLACKSMITHING],
  Hunter: [PROFESSIONS.SKINNING, PROFESSIONS.LEATHERWORKING],
  Rogue: [PROFESSIONS.SKINNING, PROFESSIONS.LEATHERWORKING],
  Druid: [PROFESSIONS.HERBALISM, PROFESSIONS.ALCHEMY],
  Priest: [PROFESSIONS.TAILORING, PROFESSIONS.ENCHANTING],
  Mage: [PROFESSIONS.TAILORING, PROFESSIONS.ENCHANTING],
  Warlock: [PROFESSIONS.TAILORING, PROFESSIONS.ENCHANTING],
};

export const PROF_ACTIONS = {
  [PROFESSIONS.MINING]: "⛏️ Mining Ore...",
  [PROFESSIONS.HERBALISM]: "🌿 Gathering Herbs...",
  [PROFESSIONS.SKINNING]: "🔪 Skinning...",
  [PROFESSIONS.BLACKSMITHING]: "🔨 Forging...",
  [PROFESSIONS.LEATHERWORKING]: "🧵 Stitching...",
  [PROFESSIONS.TAILORING]: "🧶 Weaving...",
  [PROFESSIONS.ENCHANTING]: "✨ Disenchanting...",
  [PROFESSIONS.ALCHEMY]: "⚗️ Brewing...",
};

const wowItemIcon = (iconCode) =>
  `https://wow.zamimg.com/images/wow/icons/large/${iconCode.toLowerCase()}.jpg`;

export const DB_ITEMS = [
  {
    id: 101,
    name: "Worn Shortsword",
    slot: "mainHand",
    quality: 1,
    type: "Generic",
    minLevel: 1,
  },
  {
    id: 103,
    name: "Apprentice Robe",
    slot: "chest",
    quality: 1,
    type: "Cloth",
    minLevel: 1,
  },
  {
    id: 106,
    name: "Thug's Vest",
    slot: "chest",
    quality: 1,
    type: "Leather",
    minLevel: 1,
  },
  {
    id: 109,
    name: "Rusty Chain Vest",
    slot: "chest",
    quality: 1,
    type: "Mail",
    minLevel: 1,
  },
  {
    id: 120,
    name: "Militia Hammer",
    slot: "mainHand",
    quality: 1,
    type: "Generic",
    minLevel: 6,
  },
  {
    id: 121,
    name: "Novice Linen Robe",
    slot: "chest",
    quality: 1,
    type: "Cloth",
    minLevel: 5,
  },
  {
    id: 122,
    name: "Novice Linen Pants",
    slot: "legs",
    quality: 1,
    type: "Cloth",
    minLevel: 5,
  },
  {
    id: 123,
    name: "Trailstalker Jerkin",
    slot: "chest",
    quality: 1,
    type: "Leather",
    minLevel: 5,
  },
  {
    id: 124,
    name: "Trailstalker Pants",
    slot: "legs",
    quality: 1,
    type: "Leather",
    minLevel: 5,
  },
  {
    id: 125,
    name: "Copperlinked Vest",
    slot: "chest",
    quality: 1,
    type: "Mail",
    minLevel: 5,
  },
  {
    id: 126,
    name: "Copperlinked Legguards",
    slot: "legs",
    quality: 1,
    type: "Mail",
    minLevel: 5,
  },
  {
    id: 127,
    name: "Frontier Cutlass",
    slot: "mainHand",
    quality: 1,
    type: "Generic",
    minLevel: 5,
  },
  {
    id: 128,
    name: "Adept's Wool Robe",
    slot: "chest",
    quality: 1,
    type: "Cloth",
    minLevel: 10,
  },
  {
    id: 129,
    name: "Adept's Wool Trousers",
    slot: "legs",
    quality: 1,
    type: "Cloth",
    minLevel: 10,
  },
  {
    id: 130,
    name: "Ranger Hide Tunic",
    slot: "chest",
    quality: 1,
    type: "Leather",
    minLevel: 10,
  },
  {
    id: 131,
    name: "Ranger Hide Leggings",
    slot: "legs",
    quality: 1,
    type: "Leather",
    minLevel: 10,
  },
  {
    id: 132,
    name: "Ironbound Chain Vest",
    slot: "chest",
    quality: 1,
    type: "Mail",
    minLevel: 10,
  },
  {
    id: 133,
    name: "Ironbound Chain Leggings",
    slot: "legs",
    quality: 1,
    type: "Mail",
    minLevel: 10,
  },
  {
    id: 134,
    name: "Watchman's Mace",
    slot: "mainHand",
    quality: 1,
    type: "Generic",
    minLevel: 10,
  },
  {
    id: 135,
    name: "Spellthread Robe",
    slot: "chest",
    quality: 1,
    type: "Cloth",
    minLevel: 15,
  },
  {
    id: 136,
    name: "Spellthread Leggings",
    slot: "legs",
    quality: 1,
    type: "Cloth",
    minLevel: 15,
  },
  {
    id: 137,
    name: "Shadowrunner Vest",
    slot: "chest",
    quality: 1,
    type: "Leather",
    minLevel: 15,
  },
  {
    id: 138,
    name: "Shadowrunner Leggings",
    slot: "legs",
    quality: 1,
    type: "Leather",
    minLevel: 15,
  },
  {
    id: 139,
    name: "Steelscale Hauberk",
    slot: "chest",
    quality: 1,
    type: "Mail",
    minLevel: 15,
  },
  {
    id: 140,
    name: "Steelscale Legguards",
    slot: "legs",
    quality: 1,
    type: "Mail",
    minLevel: 15,
  },
  {
    id: 141,
    name: "Knight's Broadsword",
    slot: "mainHand",
    quality: 1,
    type: "Generic",
    minLevel: 15,
  },
  {
    id: 142,
    name: "Runeweave Vestments",
    slot: "chest",
    quality: 1,
    type: "Cloth",
    minLevel: 20,
  },
  {
    id: 143,
    name: "Runeweave Legwraps",
    slot: "legs",
    quality: 1,
    type: "Cloth",
    minLevel: 20,
  },
  {
    id: 144,
    name: "Ghosthide Armor",
    slot: "chest",
    quality: 1,
    type: "Leather",
    minLevel: 20,
  },
  {
    id: 145,
    name: "Ghosthide Legguards",
    slot: "legs",
    quality: 1,
    type: "Leather",
    minLevel: 20,
  },
  {
    id: 146,
    name: "Heavy Chain Cuirass",
    slot: "chest",
    quality: 1,
    type: "Mail",
    minLevel: 20,
  },
  {
    id: 147,
    name: "Heavy Chain Legplates",
    slot: "legs",
    quality: 1,
    type: "Mail",
    minLevel: 20,
  },
  {
    id: 148,
    name: "Legionnaire Axe",
    slot: "mainHand",
    quality: 1,
    type: "Generic",
    minLevel: 20,
  },
  {
    id: 149,
    name: "Arcanist's Silk Cowl",
    slot: "head",
    quality: 2,
    type: "Cloth",
    minLevel: 20,
  },
  {
    id: 150,
    name: "Predator Hide Gloves",
    slot: "hands",
    quality: 2,
    type: "Leather",
    minLevel: 20,
  },
  {
    id: 151,
    name: "Marshal Chain Gauntlets",
    slot: "hands",
    quality: 2,
    type: "Mail",
    minLevel: 20,
  },
  {
    id: 152,
    name: "Veteran's Spellblade",
    slot: "mainHand",
    quality: 2,
    type: "Generic",
    minLevel: 20,
  },
  {
    id: 200,
    name: "Kobold Mining Mallet",
    slot: "mainHand",
    quality: 2,
    type: "Generic",
    minLevel: 5,
  },
  {
    id: 201,
    name: "Sentinel's Hood",
    slot: "head",
    quality: 2,
    type: "Cloth",
    minLevel: 6,
  },
  {
    id: 202,
    name: "Footpad's Hood",
    slot: "head",
    quality: 2,
    type: "Leather",
    minLevel: 6,
  },
  {
    id: 203,
    name: "Militia Chain Coif",
    slot: "head",
    quality: 2,
    type: "Mail",
    minLevel: 7,
  },
  {
    id: 204,
    name: "Initiate's Mitts",
    slot: "hands",
    quality: 2,
    type: "Cloth",
    minLevel: 7,
  },
  {
    id: 205,
    name: "Tracker's Grips",
    slot: "hands",
    quality: 2,
    type: "Leather",
    minLevel: 8,
  },
  {
    id: 206,
    name: "Forgebinder Gauntlets",
    slot: "hands",
    quality: 2,
    type: "Mail",
    minLevel: 9,
  },
  {
    id: 207,
    name: "Arcane-Thread Slippers",
    slot: "feet",
    quality: 2,
    type: "Cloth",
    minLevel: 10,
  },
  {
    id: 208,
    name: "Stalker Boots",
    slot: "feet",
    quality: 2,
    type: "Leather",
    minLevel: 10,
  },
  {
    id: 209,
    name: "Reinforced Chain Boots",
    slot: "feet",
    quality: 2,
    type: "Mail",
    minLevel: 11,
  },
  {
    id: 210,
    name: "Duskwoven Leggings",
    slot: "legs",
    quality: 2,
    type: "Cloth",
    minLevel: 12,
  },
  {
    id: 211,
    name: "Nightslayer Legguards",
    slot: "legs",
    quality: 2,
    type: "Leather",
    minLevel: 12,
  },
  {
    id: 212,
    name: "Ironlinked Legguards",
    slot: "legs",
    quality: 2,
    type: "Mail",
    minLevel: 13,
  },
  {
    id: 213,
    name: "Scribe's Mantle",
    slot: "chest",
    quality: 2,
    type: "Cloth",
    minLevel: 14,
  },
  {
    id: 214,
    name: "Silentstep Jerkin",
    slot: "chest",
    quality: 2,
    type: "Leather",
    minLevel: 14,
  },
  {
    id: 215,
    name: "Gilded Chain Hauberk",
    slot: "chest",
    quality: 2,
    type: "Mail",
    minLevel: 15,
  },
  {
    id: 216,
    name: "Forest Hunter Bow",
    slot: "mainHand",
    quality: 2,
    type: "Generic",
    minLevel: 13,
  },
  {
    id: 217,
    name: "Blessed War Mace",
    slot: "mainHand",
    quality: 2,
    type: "Generic",
    minLevel: 14,
  },
  {
    id: 218,
    name: "Alchemist's Dagger",
    slot: "mainHand",
    quality: 2,
    type: "Generic",
    minLevel: 12,
  },
  {
    id: 219,
    name: "Defias Wristblade",
    slot: "mainHand",
    quality: 2,
    type: "Generic",
    minLevel: 16,
  },
  {
    id: 220,
    name: "Mooncloth Cowl",
    slot: "head",
    quality: 2,
    type: "Cloth",
    minLevel: 16,
  },
  {
    id: 221,
    name: "Wildrunner Mask",
    slot: "head",
    quality: 2,
    type: "Leather",
    minLevel: 16,
  },
  {
    id: 222,
    name: "Stormforged Helm",
    slot: "head",
    quality: 2,
    type: "Mail",
    minLevel: 17,
  },
  {
    id: 223,
    name: "Mystic Satin Robe",
    slot: "chest",
    quality: 2,
    type: "Cloth",
    minLevel: 18,
  },
  {
    id: 224,
    name: "Shadowhide Tunic",
    slot: "chest",
    quality: 2,
    type: "Leather",
    minLevel: 18,
  },
  {
    id: 225,
    name: "Silvered Bronze Breastplate",
    slot: "chest",
    quality: 2,
    type: "Mail",
    minLevel: 13,
  },
  {
    id: 226,
    name: "Blackened Defias Boots",
    slot: "feet",
    quality: 2,
    type: "Leather",
    minLevel: 13,
    dungeon: "The Deadmines",
    wowheadId: 10402,
    icon: wowItemIcon("INV_Boots_05"),
    stats: { armor: 51, agility: 3, stamina: 2 },
  },
  {
    id: 227,
    name: "Blackened Defias Gloves",
    slot: "hands",
    quality: 2,
    type: "Leather",
    minLevel: 13,
    dungeon: "The Deadmines",
    wowheadId: 10401,
    icon: wowItemIcon("INV_Gauntlets_04"),
    stats: { armor: 46, strength: 3, stamina: 1 },
  },
  {
    id: 228,
    name: "Blackened Defias Leggings",
    slot: "legs",
    quality: 2,
    type: "Leather",
    minLevel: 13,
    dungeon: "The Deadmines",
    wowheadId: 10400,
    icon: wowItemIcon("INV_Pants_02"),
    stats: { armor: 65, strength: 3, agility: 3 },
  },
  {
    id: 229,
    name: "Gold-flecked Gloves",
    slot: "hands",
    quality: 2,
    type: "Cloth",
    minLevel: 14,
    dungeon: "The Deadmines",
    wowheadId: 5195,
    icon: wowItemIcon("INV_Gauntlets_05"),
    stats: { armor: 31, strength: 4, intellect: 3 },
  },
  {
    id: 230,
    name: "Armor of the Fang",
    slot: "chest",
    quality: 2,
    type: "Leather",
    minLevel: 15,
    dungeon: "Wailing Caverns",
    wowheadId: 6473,
    icon: wowItemIcon("INV_Chest_Leather_04"),
    stats: { armor: 89, strength: 8, agility: 8 },
  },
  {
    id: 231,
    name: "Gloves of the Fang",
    slot: "hands",
    quality: 2,
    type: "Leather",
    minLevel: 15,
    dungeon: "Wailing Caverns",
    wowheadId: 10413,
    icon: wowItemIcon("INV_Gauntlets_18"),
    stats: { armor: 46, stamina: 4, agility: 4 },
  },
  {
    id: 232,
    name: "Leggings of the Fang",
    slot: "legs",
    quality: 3,
    type: "Leather",
    minLevel: 16,
    dungeon: "Wailing Caverns",
    wowheadId: 10410,
    icon: wowItemIcon("INV_Pants_11"),
    stats: { armor: 66, strength: 4, agility: 5 },
  },
  {
    id: 233,
    name: "Footpads of the Fang",
    slot: "feet",
    quality: 2,
    type: "Leather",
    minLevel: 14,
    dungeon: "Wailing Caverns",
    wowheadId: 10411,
    icon: wowItemIcon("INV_Boots_04"),
    stats: { armor: 38, stamina: 3, spirit: 3 },
  },
  {
    id: 234,
    name: "Robe of the Moccasin",
    slot: "chest",
    quality: 2,
    type: "Cloth",
    minLevel: 15,
    dungeon: "Wailing Caverns",
    wowheadId: 6465,
    icon: wowItemIcon("INV_Chest_Cloth_17"),
    stats: { armor: 54, spirit: 6, intellect: 5 },
  },
  {
    id: 235,
    name: "Bloody Apron",
    slot: "chest",
    quality: 2,
    type: "Cloth",
    minLevel: 20,
    dungeon: "Shadowfang Keep",
    wowheadId: 6226,
    icon: wowItemIcon("INV_Shirt_Red_01"),
    stats: { armor: 58, stamina: 3, spirit: 4, intellect: 5 },
  },
  {
    id: 236,
    name: "Butcher's Slicer",
    slot: "mainHand",
    quality: 2,
    type: "Generic",
    minLevel: 20,
    dungeon: "Shadowfang Keep",
    wowheadId: 6633,
    icon: wowItemIcon("INV_Sword_24"),
    stats: { strength: 4 },
  },
  {
    id: 237,
    name: "Butcher's Cleaver",
    slot: "mainHand",
    quality: 2,
    type: "Generic",
    minLevel: 20,
    dungeon: "Shadowfang Keep",
    wowheadId: 1292,
    icon: wowItemIcon("INV_Axe_16"),
    stats: { strength: 3 },
  },
  {
    id: 238,
    name: "Baron's Scepter",
    slot: "mainHand",
    quality: 2,
    type: "Generic",
    minLevel: 20,
    dungeon: "Shadowfang Keep",
    wowheadId: 6323,
    icon: wowItemIcon("INV_Mace_03"),
    stats: { intellect: 3, spirit: 4 },
  },
  {
    id: 239,
    name: "Arced War Axe",
    slot: "mainHand",
    quality: 3,
    type: "Generic",
    minLevel: 21,
    dungeon: "Shadowfang Keep",
    wowheadId: 3191,
    icon: wowItemIcon("INV_Axe_17"),
    stats: { strength: 7 },
  },
  {
    id: 240,
    name: "Odo's Ley Staff",
    slot: "mainHand",
    quality: 3,
    type: "Generic",
    minLevel: 21,
    dungeon: "Shadowfang Keep",
    wowheadId: 6318,
    icon: wowItemIcon("INV_Staff_08"),
    stats: { stamina: 5, spirit: 12 },
  },
  {
    id: 241,
    name: "Haunting Blade",
    slot: "mainHand",
    quality: 3,
    type: "Generic",
    minLevel: 21,
    dungeon: "Shadowfang Keep",
    wowheadId: 6641,
    icon: wowItemIcon("INV_Sword_26"),
    stats: { stamina: 4, strength: 4 },
  },
  {
    id: 242,
    name: "Phantom Armor",
    slot: "chest",
    quality: 3,
    type: "Mail",
    minLevel: 21,
    dungeon: "Shadowfang Keep",
    wowheadId: 6642,
    icon: wowItemIcon("INV_Chest_Chain_05"),
    stats: { armor: 118, stamina: 6, strength: 4 },
  },
  {
    id: 243,
    name: "Robes of Arugal",
    slot: "chest",
    quality: 3,
    type: "Cloth",
    minLevel: 22,
    dungeon: "Shadowfang Keep",
    wowheadId: 6324,
    icon: wowItemIcon("INV_Chest_Cloth_31"),
    stats: { armor: 46, agility: 3, stamina: 5, intellect: 9, spirit: 10 },
  },
  {
    id: 244,
    name: "Meteor Shard",
    slot: "mainHand",
    quality: 3,
    type: "Generic",
    minLevel: 22,
    dungeon: "Shadowfang Keep",
    wowheadId: 6220,
    icon: wowItemIcon("INV_Weapon_ShortBlade_27"),
  },
  {
    id: 245,
    name: "Assassin's Blade",
    slot: "mainHand",
    quality: 3,
    type: "Generic",
    minLevel: 19,
    dungeon: "Shadowfang Keep",
    wowheadId: 1935,
    icon: wowItemIcon("INV_Weapon_ShortBlade_15"),
    stats: { strength: 3, agility: 4 },
  },
  {
    id: 246,
    name: "Night Reaver",
    slot: "mainHand",
    quality: 3,
    type: "Generic",
    minLevel: 18,
    dungeon: "Shadowfang Keep",
    wowheadId: 1318,
    icon: wowItemIcon("INV_Axe_16"),
  },
  {
    id: 247,
    name: "Shadowfang",
    slot: "mainHand",
    quality: 3,
    type: "Generic",
    minLevel: 19,
    dungeon: "Shadowfang Keep",
    wowheadId: 1482,
    icon: wowItemIcon("INV_Sword_04"),
    stats: { stamina: 3, agility: 3 },
  },
  {
    id: 300,
    name: "Cookie's Tenderizer",
    slot: "mainHand",
    quality: 2,
    type: "Generic",
    minLevel: 15,
    dungeon: "The Deadmines",
    wowheadId: 5198,
    icon: wowItemIcon("INV_Hammer_08"),
  },
  {
    id: 302,
    name: "Cruel Barb",
    slot: "mainHand",
    quality: 3,
    type: "Generic",
    minLevel: 17,
    dungeon: "The Deadmines",
    wowheadId: 5191,
    icon: wowItemIcon("INV_Sword_24"),
    stats: { agility: 8 },
  },
  {
    id: 304,
    name: "Blackened Defias Armor",
    slot: "chest",
    quality: 3,
    type: "Leather",
    minLevel: 19,
    dungeon: "The Deadmines",
    wowheadId: 10399,
    icon: wowItemIcon("INV_Shirt_Black_01"),
    stats: { armor: 92, strength: 4, agility: 3, stamina: 11 },
  },
  {
    id: 305,
    name: "Emberweave Crown",
    slot: "head",
    quality: 3,
    type: "Cloth",
    minLevel: 18,
  },
  {
    id: 306,
    name: "Nightstalker Tunic",
    slot: "chest",
    quality: 3,
    type: "Leather",
    minLevel: 19,
  },
  {
    id: 307,
    name: "Commander's Chain Hauberk",
    slot: "chest",
    quality: 3,
    type: "Mail",
    minLevel: 19,
  },
  {
    id: 308,
    name: "Arcane Stormblade",
    slot: "mainHand",
    quality: 3,
    type: "Generic",
    minLevel: 20,
  },
  {
    id: 309,
    name: "Frostwoven Gloves",
    slot: "hands",
    quality: 3,
    type: "Cloth",
    minLevel: 18,
  },
  {
    id: 310,
    name: "Wildshifter Leggings",
    slot: "legs",
    quality: 3,
    type: "Leather",
    minLevel: 18,
  },
  {
    id: 311,
    name: "Crusader's Chain Gauntlets",
    slot: "hands",
    quality: 3,
    type: "Mail",
    minLevel: 18,
  },
  {
    id: 312,
    name: "Emberstone Staff",
    slot: "mainHand",
    quality: 3,
    type: "Generic",
    minLevel: 16,
    dungeon: "The Deadmines",
    wowheadId: 5201,
    icon: wowItemIcon("INV_Staff_13"),
    stats: { spirit: 6, stamina: 5 },
  },
  {
    id: 313,
    name: "Smite's Reaver",
    slot: "mainHand",
    quality: 2,
    type: "Generic",
    minLevel: 17,
    dungeon: "The Deadmines",
    wowheadId: 5194,
    icon: wowItemIcon("INV_Sword_17"),
    stats: { strength: 8 },
  },
  {
    id: 314,
    name: "Venomstrike",
    slot: "mainHand",
    quality: 3,
    type: "Generic",
    minLevel: 19,
    dungeon: "Wailing Caverns",
    wowheadId: 6469,
    icon: wowItemIcon("INV_Weapon_Bow_13"),
    stats: { agility: 7 },
  },
  {
    id: 315,
    name: "Tail Spike",
    slot: "mainHand",
    quality: 2,
    type: "Generic",
    minLevel: 18,
    dungeon: "Wailing Caverns",
    wowheadId: 6448,
    icon: wowItemIcon("INV_Weapon_ShortBlade_10"),
    stats: { strength: 4 },
  },
  {
    id: 316,
    name: "Stinging Viper",
    slot: "mainHand",
    quality: 3,
    type: "Generic",
    minLevel: 17,
    dungeon: "Wailing Caverns",
    wowheadId: 6472,
    icon: wowItemIcon("INV_Wand_10"),
    stats: { stamina: 5 },
  },
];

export const DB_CLASSES = {
  Warrior: {
    color: "#C79C6E",
    icon: "https://wow.zamimg.com/images/wow/icons/medium/classicon_warrior.jpg",
    allowedRoles: ["Tank", "DPS"],
    armorTypes: ["Mail", "Leather", "Cloth"],
  },
  Paladin: {
    color: "#F58CBA",
    icon: "https://wow.zamimg.com/images/wow/icons/medium/classicon_paladin.jpg",
    allowedRoles: ["Tank", "Healer", "DPS"],
    armorTypes: ["Mail", "Leather", "Cloth"],
  },
  Hunter: {
    color: "#ABD473",
    icon: "https://wow.zamimg.com/images/wow/icons/medium/classicon_hunter.jpg",
    allowedRoles: ["DPS"],
    armorTypes: ["Leather", "Cloth"],
  },
  Rogue: {
    color: "#FFF569",
    icon: "https://wow.zamimg.com/images/wow/icons/medium/classicon_rogue.jpg",
    allowedRoles: ["DPS"],
    armorTypes: ["Leather", "Cloth"],
  },
  Priest: {
    color: "#FFFFFF",
    icon: "https://wow.zamimg.com/images/wow/icons/medium/classicon_priest.jpg",
    allowedRoles: ["Healer", "DPS"],
    armorTypes: ["Cloth"],
  },
  Mage: {
    color: "#40C7EB",
    icon: "https://wow.zamimg.com/images/wow/icons/medium/classicon_mage.jpg",
    allowedRoles: ["DPS"],
    armorTypes: ["Cloth"],
  },
  Warlock: {
    color: "#8787ED",
    icon: "https://wow.zamimg.com/images/wow/icons/medium/classicon_warlock.jpg",
    allowedRoles: ["DPS"],
    armorTypes: ["Cloth"],
  },
  Druid: {
    color: "#FF7D0A",
    icon: "https://wow.zamimg.com/images/wow/icons/medium/classicon_druid.jpg",
    allowedRoles: ["Tank", "Healer", "DPS"],
    armorTypes: ["Leather", "Cloth"],
  },
};

export const DB_RACES = {
  Human: ["Warrior", "Paladin", "Rogue", "Priest", "Mage", "Warlock"],
  Dwarf: ["Warrior", "Paladin", "Hunter", "Rogue", "Priest"],
  "Night Elf": ["Warrior", "Hunter", "Rogue", "Priest", "Druid"],
  Gnome: ["Warrior", "Rogue", "Mage", "Warlock"],
};

export const DB_NAMES = {
  Human: {
    Male: ["Varian", "Anduin", "Bolvar"],
    Female: ["Jaina", "Vanessa", "Tess"],
  },
  "Night Elf": {
    Male: ["Malfurion", "Illidan", "Jarod"],
    Female: ["Tyrande", "Shandris", "Maiev"],
  },
  Dwarf: {
    Male: ["Magni", "Muradin", "Brann"],
    Female: ["Moira", "Fenella", "Dorna"],
  },
  Gnome: {
    Male: ["Gelbin", "Mekkatorque", "Sicco"],
    Female: ["Kinndy", "Kelsey", "Pippi"],
  },
};

export const DB_LASTNAMES = [
  "Lightbringer",
  "Proudmoore",
  "Bronzebeard",
  "Whisperwind",
  "Stormrage",
  "Hellscream",
  "Menethil",
  "Fordring",
];
