const GAME_MAX_SUPPORTED_LEVEL = 60;
const QUEST_EXP_FACTOR = 0.42;
const ELITE_QUEST_EXP_FACTOR = 0.72;
const DUNGEON_EXP_FACTOR = 1.85;

const roundDownToHundred = (value) => Math.floor(value / 100) * 100;

const getXpToNextLevel = (level) => {
  const cl = Math.max(
    1,
    Math.min(GAME_MAX_SUPPORTED_LEVEL, Number(level) || 1),
  );
  const mxp = 45 + 5 * cl;

  let diff = 0;
  if (cl === 29) diff = 1;
  else if (cl === 30) diff = 3;
  else if (cl === 31) diff = 6;
  else if (cl >= 32 && cl <= 59) diff = 5 * (cl - 30);

  let rf = 1;
  if (cl >= 11 && cl <= 27) rf = 1 - (cl - 10) / 100;
  else if (cl >= 28 && cl <= 59) rf = 0.82;

  return roundDownToHundred((8 * cl + diff) * mxp * rf);
};

const buildXpTable = (maxLevel) => {
  const table = [0];
  for (let level = 1; level <= maxLevel; level++) {
    table.push(getXpToNextLevel(level));
  }
  return table;
};

const getQuestMissionExp = (level, elite = false) => {
  const factor = elite ? ELITE_QUEST_EXP_FACTOR : QUEST_EXP_FACTOR;
  const minExp = elite ? 300 : 200;
  return Math.max(minExp, roundDownToHundred(getXpToNextLevel(level) * factor));
};

const getRecommendedMaxLevel = (recommended, fallbackLevel) => {
  if (typeof recommended !== "string") return fallbackLevel;
  const values = recommended.match(/\d+/g);
  if (!values || values.length < 2) return fallbackLevel;
  const maxLevel = Number(values[1]);
  return Number.isFinite(maxLevel) ? maxLevel : fallbackLevel;
};

const getDungeonMissionExp = (recommended, fallbackLevel) => {
  const targetLevel = getRecommendedMaxLevel(recommended, fallbackLevel);
  return Math.max(1000, roundDownToHundred(getXpToNextLevel(targetLevel) * DUNGEON_EXP_FACTOR));
};

export const CONFIG = {
  MAX_ROSTER: 10,
  GOLD_CAP: 1000,
  // Active progression phase for now. Raise this toward MAX_SUPPORTED_LEVEL over time.
  LEVEL_CAP: 30,
  MAX_SUPPORTED_LEVEL: GAME_MAX_SUPPORTED_LEVEL,
  TICK_RATE: 1000,
  XP_TABLE: buildXpTable(GAME_MAX_SUPPORTED_LEVEL),
};

const getQuestDuration = (level, elite = false) => {
  let baseDuration;
  if (level < 10) {
    // Early leveling stays fast: 8s - 15s
    baseDuration = Math.min(15, 8 + Math.max(0, level - 1));
  } else if (level < 20) {
    // Mid band: 15s - 20s
    baseDuration = Math.min(20, 15 + Math.floor((level - 10) / 2));
  } else {
    // High band: 20s - 30s
    baseDuration = Math.min(30, 20 + Math.floor((level - 20) * 1.5));
  }
  return elite ? baseDuration * 2 : baseDuration;
};

const getQuestRewardQualities = (level, elite = false) => {
  if (elite) return level >= 18 ? [3] : [2];
  return level >= 12 ? [2] : [1];
};

export const INITIAL_MISSIONS = [
  {
    id: 1,
    type: "quest",
    typeLabel: "Quest",
    name: "Clear Kobold Mine",
    level: 1,
    duration: getQuestDuration(1),
    exp: getQuestMissionExp(1),
    gold: 1,
    rewardQualities: getQuestRewardQualities(1),
    elite: false,
  },
  {
    id: 2,
    type: "quest",
    typeLabel: "Quest",
    name: "Gather Herbs",
    level: 2,
    duration: getQuestDuration(2),
    exp: getQuestMissionExp(2),
    gold: 2,
    rewardQualities: getQuestRewardQualities(2),
    elite: false,
  },
  {
    id: 3,
    type: "quest",
    typeLabel: "Quest",
    name: "Wolf Hunt",
    level: 5,
    duration: getQuestDuration(5),
    exp: getQuestMissionExp(5),
    gold: 4,
    rewardQualities: getQuestRewardQualities(5),
    elite: false,
  },
  {
    id: 4,
    type: "quest",
    typeLabel: "Elite Quest",
    name: "Elite: Defeat Hogger",
    level: 10,
    duration: getQuestDuration(10, true),
    exp: getQuestMissionExp(10, true),
    gold: 8,
    rewardQualities: getQuestRewardQualities(10, true),
    elite: true,
  },
  {
    id: 8,
    type: "quest",
    typeLabel: "Quest",
    name: "Secure the Westfall Roads",
    level: 8,
    duration: getQuestDuration(8),
    exp: getQuestMissionExp(8),
    gold: 5,
    rewardQualities: getQuestRewardQualities(8),
    elite: false,
  },
  {
    id: 9,
    type: "quest",
    typeLabel: "Quest",
    name: "Purge the Moonbrook Cellar",
    level: 12,
    duration: getQuestDuration(12),
    exp: getQuestMissionExp(12),
    gold: 6,
    rewardQualities: getQuestRewardQualities(12),
    elite: false,
  },
  {
    id: 10,
    type: "quest",
    typeLabel: "Quest",
    name: "Escort the Iron Caravan",
    level: 14,
    duration: getQuestDuration(14),
    exp: getQuestMissionExp(14),
    gold: 7,
    rewardQualities: getQuestRewardQualities(14),
    elite: false,
  },
  {
    id: 11,
    type: "quest",
    typeLabel: "Quest",
    name: "Recover Stolen Reagents",
    level: 16,
    duration: getQuestDuration(16),
    exp: getQuestMissionExp(16),
    gold: 8,
    rewardQualities: getQuestRewardQualities(16),
    elite: false,
  },
  {
    id: 12,
    type: "quest",
    typeLabel: "Quest",
    name: "Hunt the Darkfang Pack",
    level: 18,
    duration: getQuestDuration(18),
    exp: getQuestMissionExp(18),
    gold: 9,
    rewardQualities: getQuestRewardQualities(18),
    elite: false,
  },
  {
    id: 13,
    type: "quest",
    typeLabel: "Quest",
    name: "Defend Sentinel Hill",
    level: 21,
    duration: getQuestDuration(21),
    exp: getQuestMissionExp(21),
    gold: 11,
    rewardQualities: getQuestRewardQualities(21),
    elite: false,
  },
  {
    id: 14,
    type: "quest",
    typeLabel: "Quest",
    name: "Assault on Ravenclaw Camp",
    level: 24,
    duration: getQuestDuration(24),
    exp: getQuestMissionExp(24),
    gold: 13,
    rewardQualities: getQuestRewardQualities(24),
    elite: false,
  },
  {
    id: 15,
    type: "quest",
    typeLabel: "Elite Quest",
    name: "Elite: Break the Defias Siege",
    level: 14,
    duration: getQuestDuration(14, true),
    exp: getQuestMissionExp(14, true),
    gold: 12,
    rewardQualities: getQuestRewardQualities(14, true),
    elite: true,
  },
  {
    id: 16,
    type: "quest",
    typeLabel: "Elite Quest",
    name: "Elite: Slay the Nightbane Alpha",
    level: 18,
    duration: getQuestDuration(18, true),
    exp: getQuestMissionExp(18, true),
    gold: 15,
    rewardQualities: getQuestRewardQualities(18, true),
    elite: true,
  },
  {
    id: 17,
    type: "quest",
    typeLabel: "Elite Quest",
    name: "Elite: Hold the Bridge at Dawn",
    level: 21,
    duration: getQuestDuration(21, true),
    exp: getQuestMissionExp(21, true),
    gold: 18,
    rewardQualities: getQuestRewardQualities(21, true),
    elite: true,
  },
  {
    id: 18,
    type: "quest",
    typeLabel: "Elite Quest",
    name: "Elite: Purge the Shadow Altar",
    level: 24,
    duration: getQuestDuration(24, true),
    exp: getQuestMissionExp(24, true),
    gold: 21,
    rewardQualities: getQuestRewardQualities(24, true),
    elite: true,
  },
  {
    id: 19,
    type: "quest",
    typeLabel: "Quest",
    name: "Stabilize the Redridge Front",
    level: 26,
    duration: getQuestDuration(26),
    exp: getQuestMissionExp(26),
    gold: 14,
    rewardQualities: getQuestRewardQualities(26),
    elite: false,
  },
  {
    id: 20,
    type: "quest",
    typeLabel: "Elite Quest",
    name: "Elite: Silence the Dread Cult",
    level: 27,
    duration: getQuestDuration(27, true),
    exp: getQuestMissionExp(27, true),
    gold: 24,
    rewardQualities: getQuestRewardQualities(27, true),
    elite: true,
  },
  {
    id: 21,
    type: "quest",
    typeLabel: "Quest",
    name: "Hold the Arathi Pass",
    level: 30,
    duration: getQuestDuration(30),
    exp: getQuestMissionExp(30),
    gold: 16,
    rewardQualities: getQuestRewardQualities(30),
    elite: false,
  },
  {
    id: 5,
    type: "dungeon",
    typeLabel: "Dungeon",
    name: "The Deadmines",
    level: 17,
    minLevel: 10,
    duration: 120,
    exp: getDungeonMissionExp("18 - 23", 17),
    gold: 15,
    rewardQualities: [2, 3],
    dungeonLootTable: {
      boss: [
        { quality: 2, chance: 80 },
        { quality: 3, chance: 20 },
      ],
      endboss: [
        { quality: 3, chance: 80 },
        { quality: 2, chance: 20 },
      ],
    },
    elite: true,
    recommended: "18 - 23",
  },
  {
    id: 6,
    type: "dungeon",
    typeLabel: "Dungeon",
    name: "Wailing Caverns",
    level: 18,
    minLevel: 10,
    duration: 150,
    exp: getDungeonMissionExp("15 - 25", 18),
    gold: 15,
    rewardQualities: [2, 3],
    dungeonLootTable: {
      boss: [
        { quality: 2, chance: 80 },
        { quality: 3, chance: 20 },
      ],
      endboss: [
        { quality: 3, chance: 80 },
        { quality: 2, chance: 20 },
      ],
    },
    elite: true,
    recommended: "15 - 25",
  },
  {
    id: 7,
    type: "dungeon",
    typeLabel: "Dungeon",
    name: "Shadowfang Keep",
    level: 22,
    minLevel: 15,
    duration: 200,
    exp: getDungeonMissionExp("22 - 30", 22),
    gold: 18,
    rewardQualities: [2, 3],
    dungeonLootTable: {
      boss: [
        { quality: 3, chance: 80 },
        { quality: 2, chance: 20 },
      ],
      endboss: [{ quality: 3, chance: 100 }],
    },
    elite: true,
    recommended: "22 - 30",
  },
  {
    id: 22,
    type: "dungeon",
    typeLabel: "Dungeon",
    name: "Blackfathom Deeps",
    level: 24,
    minLevel: 18,
    duration: 220,
    exp: getDungeonMissionExp("24 - 32", 24),
    gold: 22,
    rewardQualities: [2, 3],
    dungeonLootTable: {
      boss: [
        { quality: 3, chance: 80 },
        { quality: 2, chance: 20 },
      ],
      endboss: [{ quality: 3, chance: 100 }],
    },
    elite: true,
    recommended: "24 - 32",
  },
  {
    id: 23,
    type: "dungeon",
    typeLabel: "Dungeon",
    name: "Gnomeregan",
    level: 29,
    minLevel: 19,
    duration: 240,
    exp: getDungeonMissionExp("29 - 34", 29),
    gold: 24,
    rewardQualities: [2, 3],
    // From Gnomeregan onward: Boss 1 can drop uncommon, later bosses are rare-only.
    dungeonLootTable: {
      steps: [
        [
          { quality: 3, chance: 80 },
          { quality: 2, chance: 20 },
        ],
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
        [{ quality: 3, chance: 100 }],
      ],
    },
    elite: true,
    recommended: "29 - 34",
  },
];

export const PROFESSIONS = Object.freeze({
  MINING: "Mining",
  HERBALISM: "Herbalism",
  SKINNING: "Skinning",
  BLACKSMITHING: "Blacksmithing",
  LEATHERWORKING: "Leatherworking",
  TAILORING: "Tailoring",
  ENCHANTING: "Enchanting",
  ALCHEMY: "Alchemy",
});

export const PROFESSIONS_LIST = Object.values(PROFESSIONS);

export const DEFAULT_PROF_PAIR = [
  PROFESSIONS.MINING,
  PROFESSIONS.HERBALISM,
];

export const PROF_PAIRS = {
  Warrior: [PROFESSIONS.MINING, PROFESSIONS.BLACKSMITHING],
  Paladin: [PROFESSIONS.MINING, PROFESSIONS.BLACKSMITHING],
  Hunter: [PROFESSIONS.SKINNING, PROFESSIONS.LEATHERWORKING],
  Rogue: [PROFESSIONS.SKINNING, PROFESSIONS.LEATHERWORKING],
  Druid: [PROFESSIONS.HERBALISM, PROFESSIONS.ALCHEMY],
  Priest: [PROFESSIONS.TAILORING, PROFESSIONS.ENCHANTING],
  Mage: [PROFESSIONS.TAILORING, PROFESSIONS.ENCHANTING],
  Warlock: [PROFESSIONS.TAILORING, PROFESSIONS.ENCHANTING],
};

export const PROF_ACTIONS = {
  [PROFESSIONS.MINING]: "⛏️ Mining Ore...",
  [PROFESSIONS.HERBALISM]: "🌿 Gathering Herbs...",
  [PROFESSIONS.SKINNING]: "🔪 Skinning...",
  [PROFESSIONS.BLACKSMITHING]: "🔨 Forging...",
  [PROFESSIONS.LEATHERWORKING]: "🧵 Stitching...",
  [PROFESSIONS.TAILORING]: "🧶 Weaving...",
  [PROFESSIONS.ENCHANTING]: "✨ Disenchanting...",
  [PROFESSIONS.ALCHEMY]: "⚗️ Brewing...",
};

const wowItemIcon = (iconCode) =>
  `https://wow.zamimg.com/images/wow/icons/large/${iconCode.toLowerCase()}.jpg`;

export const DB_ITEMS = [
  {
    id: 101,
    name: "Worn Shortsword",
    slot: "mainHand",
    quality: 1,
    type: "Generic",
    minLevel: 1,
  },
  {
    id: 103,
    name: "Apprentice Robe",
    slot: "chest",
    quality: 1,
    type: "Cloth",
    minLevel: 1,
  },
  {
    id: 106,
    name: "Thug's Vest",
    slot: "chest",
    quality: 1,
    type: "Leather",
    minLevel: 1,
  },
  {
    id: 109,
    name: "Rusty Chain Vest",
    slot: "chest",
    quality: 1,
    type: "Mail",
    minLevel: 1,
  },
  {
    id: 120,
    name: "Militia Hammer",
    slot: "mainHand",
    quality: 1,
    type: "Generic",
    minLevel: 6,
  },
  {
    id: 121,
    name: "Novice Linen Robe",
    slot: "chest",
    quality: 1,
    type: "Cloth",
    minLevel: 5,
  },
  {
    id: 122,
    name: "Novice Linen Pants",
    slot: "legs",
    quality: 1,
    type: "Cloth",
    minLevel: 5,
  },
  {
    id: 123,
    name: "Trailstalker Jerkin",
    slot: "chest",
    quality: 1,
    type: "Leather",
    minLevel: 5,
  },
  {
    id: 124,
    name: "Trailstalker Pants",
    slot: "legs",
    quality: 1,
    type: "Leather",
    minLevel: 5,
  },
  {
    id: 125,
    name: "Copperlinked Vest",
    slot: "chest",
    quality: 1,
    type: "Mail",
    minLevel: 5,
  },
  {
    id: 126,
    name: "Copperlinked Legguards",
    slot: "legs",
    quality: 1,
    type: "Mail",
    minLevel: 5,
  },
  {
    id: 127,
    name: "Frontier Cutlass",
    slot: "mainHand",
    quality: 1,
    type: "Generic",
    minLevel: 5,
  },
  {
    id: 128,
    name: "Adept's Wool Robe",
    slot: "chest",
    quality: 1,
    type: "Cloth",
    minLevel: 10,
  },
  {
    id: 129,
    name: "Adept's Wool Trousers",
    slot: "legs",
    quality: 1,
    type: "Cloth",
    minLevel: 10,
  },
  {
    id: 130,
    name: "Ranger Hide Tunic",
    slot: "chest",
    quality: 1,
    type: "Leather",
    minLevel: 10,
  },
  {
    id: 131,
    name: "Ranger Hide Leggings",
    slot: "legs",
    quality: 1,
    type: "Leather",
    minLevel: 10,
  },
  {
    id: 132,
    name: "Ironbound Chain Vest",
    slot: "chest",
    quality: 1,
    type: "Mail",
    minLevel: 10,
  },
  {
    id: 133,
    name: "Ironbound Chain Leggings",
    slot: "legs",
    quality: 1,
    type: "Mail",
    minLevel: 10,
  },
  {
    id: 134,
    name: "Watchman's Mace",
    slot: "mainHand",
    quality: 1,
    type: "Generic",
    minLevel: 10,
  },
  {
    id: 135,
    name: "Spellthread Robe",
    slot: "chest",
    quality: 1,
    type: "Cloth",
    minLevel: 15,
  },
  {
    id: 136,
    name: "Spellthread Leggings",
    slot: "legs",
    quality: 1,
    type: "Cloth",
    minLevel: 15,
  },
  {
    id: 137,
    name: "Shadowrunner Vest",
    slot: "chest",
    quality: 1,
    type: "Leather",
    minLevel: 15,
  },
  {
    id: 138,
    name: "Shadowrunner Leggings",
    slot: "legs",
    quality: 1,
    type: "Leather",
    minLevel: 15,
  },
  {
    id: 139,
    name: "Steelscale Hauberk",
    slot: "chest",
    quality: 1,
    type: "Mail",
    minLevel: 15,
  },
  {
    id: 140,
    name: "Steelscale Legguards",
    slot: "legs",
    quality: 1,
    type: "Mail",
    minLevel: 15,
  },
  {
    id: 141,
    name: "Knight's Broadsword",
    slot: "mainHand",
    quality: 1,
    type: "Generic",
    minLevel: 15,
  },
  {
    id: 142,
    name: "Runeweave Vestments",
    slot: "chest",
    quality: 1,
    type: "Cloth",
    minLevel: 20,
  },
  {
    id: 143,
    name: "Runeweave Legwraps",
    slot: "legs",
    quality: 1,
    type: "Cloth",
    minLevel: 20,
  },
  {
    id: 144,
    name: "Ghosthide Armor",
    slot: "chest",
    quality: 1,
    type: "Leather",
    minLevel: 20,
  },
  {
    id: 145,
    name: "Ghosthide Legguards",
    slot: "legs",
    quality: 1,
    type: "Leather",
    minLevel: 20,
  },
  {
    id: 146,
    name: "Heavy Chain Cuirass",
    slot: "chest",
    quality: 1,
    type: "Mail",
    minLevel: 20,
  },
  {
    id: 147,
    name: "Heavy Chain Legplates",
    slot: "legs",
    quality: 1,
    type: "Mail",
    minLevel: 20,
  },
  {
    id: 148,
    name: "Legionnaire Axe",
    slot: "mainHand",
    quality: 1,
    type: "Generic",
    minLevel: 20,
  },
  {
    id: 149,
    name: "Arcanist's Silk Cowl",
    slot: "head",
    quality: 2,
    type: "Cloth",
    minLevel: 20,
  },
  {
    id: 150,
    name: "Predator Hide Gloves",
    slot: "hands",
    quality: 2,
    type: "Leather",
    minLevel: 20,
  },
  {
    id: 151,
    name: "Marshal Chain Gauntlets",
    slot: "hands",
    quality: 2,
    type: "Mail",
    minLevel: 20,
  },
  {
    id: 152,
    name: "Veteran's Spellblade",
    slot: "mainHand",
    quality: 2,
    type: "Generic",
    minLevel: 20,
  },
  {
    id: 200,
    name: "Kobold Mining Mallet",
    slot: "mainHand",
    quality: 2,
    type: "Generic",
    minLevel: 5,
  },
  {
    id: 201,
    name: "Sentinel's Hood",
    slot: "head",
    quality: 2,
    type: "Cloth",
    minLevel: 6,
  },
  {
    id: 202,
    name: "Footpad's Hood",
    slot: "head",
    quality: 2,
    type: "Leather",
    minLevel: 6,
  },
  {
    id: 203,
    name: "Militia Chain Coif",
    slot: "head",
    quality: 2,
    type: "Mail",
    minLevel: 7,
  },
  {
    id: 204,
    name: "Initiate's Mitts",
    slot: "hands",
    quality: 2,
    type: "Cloth",
    minLevel: 7,
  },
  {
    id: 205,
    name: "Tracker's Grips",
    slot: "hands",
    quality: 2,
    type: "Leather",
    minLevel: 8,
  },
  {
    id: 206,
    name: "Forgebinder Gauntlets",
    slot: "hands",
    quality: 2,
    type: "Mail",
    minLevel: 9,
  },
  {
    id: 207,
    name: "Arcane-Thread Slippers",
    slot: "feet",
    quality: 2,
    type: "Cloth",
    minLevel: 10,
  },
  {
    id: 208,
    name: "Stalker Boots",
    slot: "feet",
    quality: 2,
    type: "Leather",
    minLevel: 10,
  },
  {
    id: 209,
    name: "Reinforced Chain Boots",
    slot: "feet",
    quality: 2,
    type: "Mail",
    minLevel: 11,
  },
  {
    id: 210,
    name: "Duskwoven Leggings",
    slot: "legs",
    quality: 2,
    type: "Cloth",
    minLevel: 12,
  },
  {
    id: 211,
    name: "Nightslayer Legguards",
    slot: "legs",
    quality: 2,
    type: "Leather",
    minLevel: 12,
  },
  {
    id: 212,
    name: "Ironlinked Legguards",
    slot: "legs",
    quality: 2,
    type: "Mail",
    minLevel: 13,
  },
  {
    id: 213,
    name: "Scribe's Mantle",
    slot: "chest",
    quality: 2,
    type: "Cloth",
    minLevel: 14,
  },
  {
    id: 214,
    name: "Silentstep Jerkin",
    slot: "chest",
    quality: 2,
    type: "Leather",
    minLevel: 14,
  },
  {
    id: 215,
    name: "Gilded Chain Hauberk",
    slot: "chest",
    quality: 2,
    type: "Mail",
    minLevel: 15,
  },
  {
    id: 216,
    name: "Forest Hunter Bow",
    slot: "mainHand",
    quality: 2,
    type: "Generic",
    minLevel: 13,
  },
  {
    id: 217,
    name: "Blessed War Mace",
    slot: "mainHand",
    quality: 2,
    type: "Generic",
    minLevel: 14,
  },
  {
    id: 218,
    name: "Alchemist's Dagger",
    slot: "mainHand",
    quality: 2,
    type: "Generic",
    minLevel: 12,
  },
  {
    id: 219,
    name: "Defias Wristblade",
    slot: "mainHand",
    quality: 2,
    type: "Generic",
    minLevel: 16,
  },
  {
    id: 220,
    name: "Mooncloth Cowl",
    slot: "head",
    quality: 2,
    type: "Cloth",
    minLevel: 16,
  },
  {
    id: 221,
    name: "Wildrunner Mask",
    slot: "head",
    quality: 2,
    type: "Leather",
    minLevel: 16,
  },
  {
    id: 222,
    name: "Stormforged Helm",
    slot: "head",
    quality: 2,
    type: "Mail",
    minLevel: 17,
  },
  {
    id: 223,
    name: "Mystic Satin Robe",
    slot: "chest",
    quality: 2,
    type: "Cloth",
    minLevel: 18,
  },
  {
    id: 224,
    name: "Shadowhide Tunic",
    slot: "chest",
    quality: 2,
    type: "Leather",
    minLevel: 18,
  },
  {
    id: 225,
    name: "Silvered Bronze Breastplate",
    slot: "chest",
    quality: 2,
    type: "Mail",
    minLevel: 13,
  },
  {
    id: 226,
    name: "Blackened Defias Boots",
    slot: "feet",
    quality: 2,
    type: "Leather",
    minLevel: 13,
    dungeon: "The Deadmines",
    wowheadId: 10402,
    icon: wowItemIcon("INV_Boots_05"),
    stats: { armor: 51, agility: 3, stamina: 2 },
  },
  {
    id: 227,
    name: "Blackened Defias Gloves",
    slot: "hands",
    quality: 2,
    type: "Leather",
    minLevel: 13,
    dungeon: "The Deadmines",
    wowheadId: 10401,
    icon: wowItemIcon("INV_Gauntlets_04"),
    stats: { armor: 46, strength: 3, stamina: 1 },
  },
  {
    id: 228,
    name: "Blackened Defias Leggings",
    slot: "legs",
    quality: 2,
    type: "Leather",
    minLevel: 13,
    dungeon: "The Deadmines",
    wowheadId: 10400,
    icon: wowItemIcon("INV_Pants_02"),
    stats: { armor: 65, strength: 3, agility: 3 },
  },
  {
    id: 229,
    name: "Gold-flecked Gloves",
    slot: "hands",
    quality: 2,
    type: "Cloth",
    minLevel: 14,
    dungeon: "The Deadmines",
    wowheadId: 5195,
    icon: wowItemIcon("INV_Gauntlets_05"),
    stats: { armor: 31, strength: 4, intellect: 3 },
  },
  {
    id: 230,
    name: "Armor of the Fang",
    slot: "chest",
    quality: 2,
    type: "Leather",
    minLevel: 15,
    dungeon: "Wailing Caverns",
    wowheadId: 6473,
    icon: wowItemIcon("INV_Chest_Leather_04"),
    stats: { armor: 89, strength: 8, agility: 8 },
  },
  {
    id: 231,
    name: "Gloves of the Fang",
    slot: "hands",
    quality: 2,
    type: "Leather",
    minLevel: 15,
    dungeon: "Wailing Caverns",
    wowheadId: 10413,
    icon: wowItemIcon("INV_Gauntlets_18"),
    stats: { armor: 46, stamina: 4, agility: 4 },
  },
  {
    id: 232,
    name: "Leggings of the Fang",
    slot: "legs",
    quality: 3,
    type: "Leather",
    minLevel: 16,
    dungeon: "Wailing Caverns",
    wowheadId: 10410,
    icon: wowItemIcon("INV_Pants_11"),
    stats: { armor: 66, strength: 4, agility: 5 },
  },
  {
    id: 233,
    name: "Footpads of the Fang",
    slot: "feet",
    quality: 2,
    type: "Leather",
    minLevel: 14,
    dungeon: "Wailing Caverns",
    wowheadId: 10411,
    icon: wowItemIcon("INV_Boots_04"),
    stats: { armor: 38, stamina: 3, spirit: 3 },
  },
  {
    id: 234,
    name: "Robe of the Moccasin",
    slot: "chest",
    quality: 2,
    type: "Cloth",
    minLevel: 15,
    dungeon: "Wailing Caverns",
    wowheadId: 6465,
    icon: wowItemIcon("INV_Chest_Cloth_17"),
    stats: { armor: 54, spirit: 6, intellect: 5 },
  },
  {
    id: 235,
    name: "Bloody Apron",
    slot: "chest",
    quality: 2,
    type: "Cloth",
    minLevel: 20,
    dungeon: "Shadowfang Keep",
    wowheadId: 6226,
    icon: wowItemIcon("INV_Shirt_Red_01"),
    stats: { armor: 58, stamina: 3, spirit: 4, intellect: 5 },
  },
  {
    id: 236,
    name: "Butcher's Slicer",
    slot: "mainHand",
    quality: 2,
    type: "Generic",
    minLevel: 20,
    dungeon: "Shadowfang Keep",
    wowheadId: 6633,
    icon: wowItemIcon("INV_Sword_24"),
    stats: { strength: 4 },
  },
  {
    id: 237,
    name: "Butcher's Cleaver",
    slot: "mainHand",
    quality: 2,
    type: "Generic",
    minLevel: 20,
    dungeon: "Shadowfang Keep",
    wowheadId: 1292,
    icon: wowItemIcon("INV_Axe_16"),
    stats: { strength: 3 },
  },
  {
    id: 238,
    name: "Baron's Scepter",
    slot: "mainHand",
    quality: 2,
    type: "Generic",
    minLevel: 20,
    dungeon: "Shadowfang Keep",
    wowheadId: 6323,
    icon: wowItemIcon("INV_Mace_03"),
    stats: { intellect: 3, spirit: 4 },
  },
  {
    id: 239,
    name: "Arced War Axe",
    slot: "mainHand",
    quality: 3,
    type: "Generic",
    minLevel: 21,
    dungeon: "Shadowfang Keep",
    wowheadId: 3191,
    icon: wowItemIcon("INV_Axe_17"),
    stats: { strength: 7 },
  },
  {
    id: 240,
    name: "Odo's Ley Staff",
    slot: "mainHand",
    quality: 3,
    type: "Generic",
    minLevel: 21,
    dungeon: "Shadowfang Keep",
    wowheadId: 6318,
    icon: wowItemIcon("INV_Staff_08"),
    stats: { stamina: 5, spirit: 12 },
  },
  {
    id: 241,
    name: "Haunting Blade",
    slot: "mainHand",
    quality: 3,
    type: "Generic",
    minLevel: 21,
    dungeon: "Shadowfang Keep",
    wowheadId: 6641,
    icon: wowItemIcon("INV_Sword_26"),
    stats: { stamina: 4, strength: 4 },
  },
  {
    id: 242,
    name: "Phantom Armor",
    slot: "chest",
    quality: 3,
    type: "Mail",
    minLevel: 21,
    dungeon: "Shadowfang Keep",
    wowheadId: 6642,
    icon: wowItemIcon("INV_Chest_Chain_05"),
    stats: { armor: 118, stamina: 6, strength: 4 },
  },
  {
    id: 243,
    name: "Robes of Arugal",
    slot: "chest",
    quality: 3,
    type: "Cloth",
    minLevel: 22,
    dungeon: "Shadowfang Keep",
    wowheadId: 6324,
    icon: wowItemIcon("INV_Chest_Cloth_31"),
    stats: { armor: 46, agility: 3, stamina: 5, intellect: 9, spirit: 10 },
  },
  {
    id: 244,
    name: "Meteor Shard",
    slot: "mainHand",
    quality: 3,
    type: "Generic",
    minLevel: 22,
    dungeon: "Shadowfang Keep",
    wowheadId: 6220,
    icon: wowItemIcon("INV_Weapon_ShortBlade_27"),
  },
  {
    id: 245,
    name: "Assassin's Blade",
    slot: "mainHand",
    quality: 3,
    type: "Generic",
    minLevel: 19,
    dungeon: "Shadowfang Keep",
    wowheadId: 1935,
    icon: wowItemIcon("INV_Weapon_ShortBlade_15"),
    stats: { strength: 3, agility: 4 },
  },
  {
    id: 246,
    name: "Night Reaver",
    slot: "mainHand",
    quality: 3,
    type: "Generic",
    minLevel: 18,
    dungeon: "Shadowfang Keep",
    wowheadId: 1318,
    icon: wowItemIcon("INV_Axe_16"),
  },
  {
    id: 247,
    name: "Shadowfang",
    slot: "mainHand",
    quality: 3,
    type: "Generic",
    minLevel: 19,
    dungeon: "Shadowfang Keep",
    wowheadId: 1482,
    icon: wowItemIcon("INV_Sword_04"),
    stats: { stamina: 3, agility: 3 },
  },
  {
    id: 300,
    name: "Cookie's Tenderizer",
    slot: "mainHand",
    quality: 2,
    type: "Generic",
    minLevel: 15,
    dungeon: "The Deadmines",
    wowheadId: 5198,
    icon: wowItemIcon("INV_Hammer_08"),
  },
  {
    id: 302,
    name: "Cruel Barb",
    slot: "mainHand",
    quality: 3,
    type: "Generic",
    minLevel: 17,
    dungeon: "The Deadmines",
    wowheadId: 5191,
    icon: wowItemIcon("INV_Sword_24"),
    stats: { agility: 8 },
  },
  {
    id: 304,
    name: "Blackened Defias Armor",
    slot: "chest",
    quality: 3,
    type: "Leather",
    minLevel: 19,
    dungeon: "The Deadmines",
    wowheadId: 10399,
    icon: wowItemIcon("INV_Shirt_Black_01"),
    stats: { armor: 92, strength: 4, agility: 3, stamina: 11 },
  },
  {
    id: 305,
    name: "Emberweave Crown",
    slot: "head",
    quality: 3,
    type: "Cloth",
    minLevel: 18,
  },
  {
    id: 306,
    name: "Nightstalker Tunic",
    slot: "chest",
    quality: 3,
    type: "Leather",
    minLevel: 19,
  },
  {
    id: 307,
    name: "Commander's Chain Hauberk",
    slot: "chest",
    quality: 3,
    type: "Mail",
    minLevel: 19,
  },
  {
    id: 308,
    name: "Arcane Stormblade",
    slot: "mainHand",
    quality: 3,
    type: "Generic",
    minLevel: 20,
  },
  {
    id: 309,
    name: "Frostwoven Gloves",
    slot: "hands",
    quality: 3,
    type: "Cloth",
    minLevel: 18,
  },
  {
    id: 310,
    name: "Wildshifter Leggings",
    slot: "legs",
    quality: 3,
    type: "Leather",
    minLevel: 18,
  },
  {
    id: 311,
    name: "Crusader's Chain Gauntlets",
    slot: "hands",
    quality: 3,
    type: "Mail",
    minLevel: 18,
  },
  {
    id: 312,
    name: "Emberstone Staff",
    slot: "mainHand",
    quality: 3,
    type: "Generic",
    minLevel: 16,
    dungeon: "The Deadmines",
    wowheadId: 5201,
    icon: wowItemIcon("INV_Staff_13"),
    stats: { spirit: 6, stamina: 5 },
  },
  {
    id: 313,
    name: "Smite's Reaver",
    slot: "mainHand",
    quality: 2,
    type: "Generic",
    minLevel: 17,
    dungeon: "The Deadmines",
    wowheadId: 5194,
    icon: wowItemIcon("INV_Sword_17"),
    stats: { strength: 8 },
  },
  {
    id: 314,
    name: "Venomstrike",
    slot: "mainHand",
    quality: 3,
    type: "Generic",
    minLevel: 19,
    dungeon: "Wailing Caverns",
    wowheadId: 6469,
    icon: wowItemIcon("INV_Weapon_Bow_13"),
    stats: { agility: 7 },
  },
  {
    id: 315,
    name: "Tail Spike",
    slot: "mainHand",
    quality: 2,
    type: "Generic",
    minLevel: 18,
    dungeon: "Wailing Caverns",
    wowheadId: 6448,
    icon: wowItemIcon("INV_Weapon_ShortBlade_10"),
    stats: { strength: 4 },
  },
  {
    id: 316,
    name: "Stinging Viper",
    slot: "mainHand",
    quality: 3,
    type: "Generic",
    minLevel: 17,
    dungeon: "Wailing Caverns",
    wowheadId: 6472,
    icon: wowItemIcon("INV_Wand_10"),
    stats: { stamina: 5 },
  },
  {
    id: 317,
    name: "Azureweave Cowl",
    slot: "head",
    quality: 2,
    type: "Cloth",
    minLevel: 21,
    icon: wowItemIcon("INV_Helmet_29"),
    stats: { intellect: 6, spirit: 4 },
  },
  {
    id: 318,
    name: "Starthread Robe",
    slot: "chest",
    quality: 2,
    type: "Cloth",
    minLevel: 24,
    icon: wowItemIcon("INV_Chest_Cloth_15"),
    stats: { intellect: 7, stamina: 5 },
  },
  {
    id: 319,
    name: "Duskmire Leggings",
    slot: "legs",
    quality: 2,
    type: "Cloth",
    minLevel: 27,
    icon: wowItemIcon("INV_Pants_06"),
    stats: { spirit: 8, stamina: 4 },
  },
  {
    id: 320,
    name: "Runebound Slippers",
    slot: "feet",
    quality: 2,
    type: "Cloth",
    minLevel: 30,
    icon: wowItemIcon("INV_Boots_07"),
    stats: { intellect: 5, spirit: 5 },
  },
  {
    id: 321,
    name: "Spiritcall Gloves",
    slot: "hands",
    quality: 2,
    type: "Cloth",
    minLevel: 26,
    icon: wowItemIcon("INV_Gauntlets_17"),
    stats: { intellect: 4, stamina: 5 },
  },
  {
    id: 322,
    name: "Tracker's Shadowcap",
    slot: "head",
    quality: 2,
    type: "Leather",
    minLevel: 21,
    icon: wowItemIcon("INV_Helmet_09"),
    stats: { agility: 6, stamina: 4 },
  },
  {
    id: 323,
    name: "Nightpelt Jerkin",
    slot: "chest",
    quality: 2,
    type: "Leather",
    minLevel: 24,
    icon: wowItemIcon("INV_Chest_Leather_09"),
    stats: { agility: 7, strength: 3, stamina: 5 },
  },
  {
    id: 324,
    name: "Windrunner Legguards",
    slot: "legs",
    quality: 2,
    type: "Leather",
    minLevel: 27,
    icon: wowItemIcon("INV_Pants_12"),
    stats: { agility: 8, stamina: 4 },
  },
  {
    id: 325,
    name: "Marshstalker Boots",
    slot: "feet",
    quality: 2,
    type: "Leather",
    minLevel: 30,
    icon: wowItemIcon("INV_Boots_05"),
    stats: { agility: 5, stamina: 6 },
  },
  {
    id: 326,
    name: "Fanghide Grips",
    slot: "hands",
    quality: 2,
    type: "Leather",
    minLevel: 26,
    icon: wowItemIcon("INV_Gauntlets_21"),
    stats: { agility: 5, strength: 3, stamina: 4 },
  },
  {
    id: 327,
    name: "Ironbark Helm",
    slot: "head",
    quality: 2,
    type: "Mail",
    minLevel: 21,
    icon: wowItemIcon("INV_Helmet_28"),
    stats: { stamina: 6, strength: 3 },
  },
  {
    id: 328,
    name: "Battlechain Hauberk",
    slot: "chest",
    quality: 2,
    type: "Mail",
    minLevel: 24,
    icon: wowItemIcon("INV_Chest_Chain_11"),
    stats: { stamina: 8, strength: 4 },
  },
  {
    id: 329,
    name: "Stoneguard Legplates",
    slot: "legs",
    quality: 2,
    type: "Mail",
    minLevel: 27,
    icon: wowItemIcon("INV_Pants_Mail_15"),
    stats: { stamina: 7, strength: 5 },
  },
  {
    id: 330,
    name: "Thunderstep Sabatons",
    slot: "feet",
    quality: 2,
    type: "Mail",
    minLevel: 30,
    icon: wowItemIcon("INV_Boots_Plate_03"),
    stats: { stamina: 6, strength: 4 },
  },
  {
    id: 331,
    name: "Vanguard Gauntlets",
    slot: "hands",
    quality: 2,
    type: "Mail",
    minLevel: 26,
    icon: wowItemIcon("INV_Gauntlets_30"),
    stats: { stamina: 5, strength: 4 },
  },
  {
    id: 332,
    name: "Ashwood Carver",
    slot: "mainHand",
    quality: 2,
    type: "Generic",
    minLevel: 22,
    icon: wowItemIcon("INV_Axe_12"),
    stats: { strength: 5 },
  },
  {
    id: 333,
    name: "Witchwood Spellblade",
    slot: "mainHand",
    quality: 2,
    type: "Generic",
    minLevel: 25,
    icon: wowItemIcon("INV_Sword_04"),
    stats: { intellect: 5, stamina: 3 },
  },
  {
    id: 334,
    name: "Reforged Defender",
    slot: "mainHand",
    quality: 2,
    type: "Generic",
    minLevel: 28,
    icon: wowItemIcon("INV_Sword_20"),
    stats: { stamina: 6, strength: 3 },
  },
  {
    id: 335,
    name: "Twilight Edge",
    slot: "mainHand",
    quality: 2,
    type: "Generic",
    minLevel: 30,
    icon: wowItemIcon("INV_Sword_38"),
    stats: { stamina: 6, agility: 4 },
  },
  {
    id: 336,
    name: "Tortoise Armor",
    slot: "chest",
    quality: 2,
    type: "Mail",
    minLevel: 24,
    dungeon: "Blackfathom Deeps",
    wowheadId: 6907,
    icon: wowItemIcon("INV_Chest_Chain_05"),
    stats: { armor: 145, stamina: 8, strength: 4 },
  },
  {
    id: 337,
    name: "Naga Battle Gloves",
    slot: "hands",
    quality: 3,
    type: "Mail",
    minLevel: 22,
    dungeon: "Blackfathom Deeps",
    wowheadId: 888,
    icon: wowItemIcon("INV_Gauntlets_10"),
    stats: { armor: 68, stamina: 4, strength: 4 },
  },
  {
    id: 338,
    name: "Algae Fists",
    slot: "hands",
    quality: 3,
    type: "Mail",
    minLevel: 22,
    dungeon: "Blackfathom Deeps",
    wowheadId: 6906,
    icon: wowItemIcon("INV_Gauntlets_04"),
    stats: { armor: 66, stamina: 4, spirit: 3 },
  },
  {
    id: 339,
    name: "Gaze Dreamer Pants",
    slot: "legs",
    quality: 2,
    type: "Cloth",
    minLevel: 21,
    dungeon: "Blackfathom Deeps",
    wowheadId: 6903,
    icon: wowItemIcon("INV_Pants_11"),
    stats: { armor: 58, intellect: 6, spirit: 6 },
  },
  {
    id: 340,
    name: "Leech Pants",
    slot: "legs",
    quality: 3,
    type: "Leather",
    minLevel: 22,
    dungeon: "Blackfathom Deeps",
    wowheadId: 6910,
    icon: wowItemIcon("INV_Pants_02"),
    stats: { armor: 87, agility: 6, stamina: 5 },
  },
  {
    id: 341,
    name: "Reef Axe",
    slot: "mainHand",
    quality: 2,
    type: "Generic",
    minLevel: 24,
    dungeon: "Blackfathom Deeps",
    wowheadId: 6905,
    icon: wowItemIcon("INV_Axe_11"),
    stats: { strength: 5 },
  },
  {
    id: 342,
    name: "Naga Heartpiercer",
    slot: "mainHand",
    quality: 2,
    type: "Generic",
    minLevel: 20,
    dungeon: "Blackfathom Deeps",
    wowheadId: 3078,
    icon: wowItemIcon("INV_Spear_06"),
    stats: { agility: 4 },
  },
  {
    id: 343,
    name: "Darkwater Talwar",
    slot: "mainHand",
    quality: 2,
    type: "Generic",
    minLevel: 24,
    dungeon: "Blackfathom Deeps",
    wowheadId: 11121,
    icon: wowItemIcon("INV_Sword_25"),
    stats: { strength: 4, agility: 2 },
  },
  {
    id: 344,
    name: "Bite of Serra'kis",
    slot: "mainHand",
    quality: 3,
    type: "Generic",
    minLevel: 22,
    dungeon: "Blackfathom Deeps",
    wowheadId: 6904,
    icon: wowItemIcon("INV_Weapon_ShortBlade_18"),
    stats: { agility: 5, stamina: 3 },
  },
  {
    id: 345,
    name: "Rod of the Sleepwalker",
    slot: "mainHand",
    quality: 3,
    type: "Generic",
    minLevel: 21,
    dungeon: "Blackfathom Deeps",
    wowheadId: 1155,
    icon: wowItemIcon("INV_Staff_20"),
    stats: { intellect: 8, spirit: 8 },
  },
  {
    id: 346,
    name: "Strike of the Hydra",
    slot: "mainHand",
    quality: 3,
    type: "Generic",
    minLevel: 22,
    dungeon: "Blackfathom Deeps",
    wowheadId: 6909,
    icon: wowItemIcon("INV_Sword_39"),
    stats: { strength: 7, stamina: 4 },
  },
  {
    id: 347,
    name: "Grubbis Paws",
    slot: "hands",
    quality: 2,
    type: "Leather",
    minLevel: 29,
    dungeon: "Gnomeregan",
    wowheadId: 9445,
    icon: wowItemIcon("INV_Gauntlets_05"),
    stats: { agility: 6, stamina: 3 },
  },
  {
    id: 348,
    name: "Acidic Walkers",
    slot: "feet",
    quality: 2,
    type: "Cloth",
    minLevel: 27,
    dungeon: "Gnomeregan",
    wowheadId: 9454,
    icon: wowItemIcon("INV_Boots_06"),
    stats: { spirit: 5, stamina: 4 },
  },
  {
    id: 349,
    name: "Hydrocane",
    slot: "mainHand",
    quality: 3,
    type: "Generic",
    minLevel: 27,
    dungeon: "Gnomeregan",
    wowheadId: 9452,
    icon: wowItemIcon("INV_Staff_16"),
    stats: { spirit: 8, stamina: 4 },
  },
  {
    id: 350,
    name: "Toxic Revenger",
    slot: "mainHand",
    quality: 3,
    type: "Generic",
    minLevel: 27,
    dungeon: "Gnomeregan",
    wowheadId: 9453,
    icon: wowItemIcon("INV_Weapon_ShortBlade_07"),
    stats: { agility: 5, stamina: 3 },
  },
  {
    id: 351,
    name: "Electrocutioner Leg",
    slot: "mainHand",
    quality: 3,
    type: "Generic",
    minLevel: 29,
    dungeon: "Gnomeregan",
    wowheadId: 9446,
    icon: wowItemIcon("INV_Mace_08"),
    stats: { strength: 6, stamina: 3 },
  },
  {
    id: 352,
    name: "Gnomebot Operating Boots",
    slot: "feet",
    quality: 3,
    type: "Mail",
    minLevel: 28,
    dungeon: "Gnomeregan",
    wowheadId: 9450,
    icon: wowItemIcon("INV_Boots_Plate_03"),
    stats: { armor: 121, stamina: 6, strength: 4 },
  },
  {
    id: 353,
    name: "Manual Crowd Pummeler",
    slot: "mainHand",
    quality: 3,
    type: "Generic",
    minLevel: 29,
    dungeon: "Gnomeregan",
    wowheadId: 9449,
    icon: wowItemIcon("INV_Mace_14"),
    stats: { strength: 8, agility: 4 },
  },
  {
    id: 354,
    name: "Glass Shooter",
    slot: "mainHand",
    quality: 3,
    type: "Generic",
    minLevel: 30,
    dungeon: "Gnomeregan",
    wowheadId: 9456,
    icon: wowItemIcon("INV_Weapon_Rifle_08"),
    stats: { agility: 6 },
  },
  {
    id: 355,
    name: "Royal Diplomatic Scepter",
    slot: "mainHand",
    quality: 3,
    type: "Generic",
    minLevel: 30,
    dungeon: "Gnomeregan",
    wowheadId: 9457,
    icon: wowItemIcon("INV_Staff_13"),
    stats: { intellect: 8, spirit: 6 },
  },
  {
    id: 356,
    name: "Electromagnetic Gigaflux Reactivator",
    slot: "head",
    quality: 3,
    type: "Mail",
    minLevel: 32,
    dungeon: "Gnomeregan",
    wowheadId: 9492,
    icon: wowItemIcon("INV_Helmet_18"),
    stats: { armor: 196, stamina: 10, strength: 6 },
  },
  {
    id: 357,
    name: "Thermaplugg's Left Arm",
    slot: "mainHand",
    quality: 3,
    type: "Generic",
    minLevel: 32,
    dungeon: "Gnomeregan",
    wowheadId: 9459,
    icon: wowItemIcon("INV_Weapon_ShortBlade_30"),
    stats: { strength: 7, stamina: 7 },
  },
];

export const DB_CLASSES = {
  Warrior: {
    color: "#C79C6E",
    icon: "https://wow.zamimg.com/images/wow/icons/medium/classicon_warrior.jpg",
    allowedRoles: ["Tank", "DPS"],
    armorTypes: ["Mail", "Leather", "Cloth"],
  },
  Paladin: {
    color: "#F58CBA",
    icon: "https://wow.zamimg.com/images/wow/icons/medium/classicon_paladin.jpg",
    allowedRoles: ["Tank", "Healer", "DPS"],
    armorTypes: ["Mail", "Leather", "Cloth"],
  },
  Hunter: {
    color: "#ABD473",
    icon: "https://wow.zamimg.com/images/wow/icons/medium/classicon_hunter.jpg",
    allowedRoles: ["DPS"],
    armorTypes: ["Leather", "Cloth"],
  },
  Rogue: {
    color: "#FFF569",
    icon: "https://wow.zamimg.com/images/wow/icons/medium/classicon_rogue.jpg",
    allowedRoles: ["DPS"],
    armorTypes: ["Leather", "Cloth"],
  },
  Priest: {
    color: "#FFFFFF",
    icon: "https://wow.zamimg.com/images/wow/icons/medium/classicon_priest.jpg",
    allowedRoles: ["Healer", "DPS"],
    armorTypes: ["Cloth"],
  },
  Mage: {
    color: "#40C7EB",
    icon: "https://wow.zamimg.com/images/wow/icons/medium/classicon_mage.jpg",
    allowedRoles: ["DPS"],
    armorTypes: ["Cloth"],
  },
  Warlock: {
    color: "#8787ED",
    icon: "https://wow.zamimg.com/images/wow/icons/medium/classicon_warlock.jpg",
    allowedRoles: ["DPS"],
    armorTypes: ["Cloth"],
  },
  Druid: {
    color: "#FF7D0A",
    icon: "https://wow.zamimg.com/images/wow/icons/medium/classicon_druid.jpg",
    allowedRoles: ["Tank", "Healer", "DPS"],
    armorTypes: ["Leather", "Cloth"],
  },
};

export const DB_RACES = {
  Human: ["Warrior", "Paladin", "Rogue", "Priest", "Mage", "Warlock"],
  Dwarf: ["Warrior", "Paladin", "Hunter", "Rogue", "Priest"],
  "Night Elf": ["Warrior", "Hunter", "Rogue", "Priest", "Druid"],
  Gnome: ["Warrior", "Rogue", "Mage", "Warlock"],
};

export const DB_NAMES = {
  Human: {
    Male: ["Varian", "Anduin", "Bolvar"],
    Female: ["Jaina", "Vanessa", "Tess"],
  },
  "Night Elf": {
    Male: ["Malfurion", "Illidan", "Jarod"],
    Female: ["Tyrande", "Shandris", "Maiev"],
  },
  Dwarf: {
    Male: ["Magni", "Muradin", "Brann"],
    Female: ["Moira", "Fenella", "Dorna"],
  },
  Gnome: {
    Male: ["Gelbin", "Mekkatorque", "Sicco"],
    Female: ["Kinndy", "Kelsey", "Pippi"],
  },
};

export const DB_LASTNAMES = [
  "Lightbringer",
  "Proudmoore",
  "Bronzebeard",
  "Whisperwind",
  "Stormrage",
  "Hellscream",
  "Menethil",
  "Fordring",
];
