export const ROUTES = Object.freeze({
  START: "/start",
  HOME: "/home",
  DASHBOARD: "/home",
  GUILD: "/home/guild",
  RECRUIT: "/home/recruit",
  CALENDAR: "/home/calendar",
  REALM: "/home/realm",
  MISSION_BOARD: "/home/mission-board",
  ADVENTURE_BOARD: "/home/adventure-board",
  DUNGEON_BOARD: "/home/dungeon-board",
  DUNGEON_BOARD_ALIAS: "/dungeon-board",
  BATTLEFIELDS: "/home/battlefields",
  BATTLEFIELDS_ALIAS: "/battlefields",
  PROFESSIONS: "/home/professions",
  DATABASE: "/home/database",
  GUILD_LOG: "/home/guild-log",
  CHAT: "/home/chat",
});
