import { mkdir, readFile, writeFile } from "node:fs/promises";

type CatalogItem = {
  dungeonSetId?: string;
  icon?: string;
  wowheadId?: number;
};

const RAID_SOURCE_IDS = new Set([
  "molten_core",
  "zul_gurub",
  "ahn_qiraj_ruins",
  "onyxias_lair",
  "blackwing_lair",
  "ahn_qiraj_temple",
  "naxxramas",
]);
const QUESTION_MARK_ICON = "inv_misc_questionmark";
const MAX_CONCURRENT_REQUESTS = 12;
const catalogFile = new URL(
  "../public/generated/item-catalog-v15.json",
  import.meta.url,
);
const DB_ITEMS = JSON.parse(
  await readFile(catalogFile, "utf8"),
) as CatalogItem[];

const candidates = DB_ITEMS.filter((item) => {
  const wowheadId = Number(item.wowheadId);
  if (!Number.isFinite(wowheadId) || wowheadId <= 0) return false;
  return (
    RAID_SOURCE_IDS.has(String(item.dungeonSetId || "")) ||
    String(item.icon || "").toLowerCase().includes(QUESTION_MARK_ICON)
  );
});
const wowheadIds: number[] = [
  ...new Set(candidates.map((item) => Number(item.wowheadId))),
].sort((left, right) => left - right);

const fetchIcon = async (wowheadId: number) => {
  const endpoint = `https://nether.wowhead.com/classic/tooltip/item/${wowheadId}?dataEnv=1&locale=0`;
  let lastError: unknown = null;
  for (let attempt = 1; attempt <= 3; attempt += 1) {
    try {
      const response = await fetch(endpoint, {
        headers: { "user-agent": "guild-manager-item-icon-sync/1.0" },
      });
      if (!response.ok) {
        throw new Error(`HTTP ${response.status}`);
      }
      const payload = (await response.json()) as {
        icon?: unknown;
        name?: unknown;
      };
      const icon = String(payload.icon || "").trim().toLowerCase();
      if (!icon || icon === QUESTION_MARK_ICON) {
        throw new Error("Tooltip did not provide a canonical icon");
      }
      return { wowheadId, icon };
    } catch (error) {
      lastError = error;
      if (attempt < 3) {
        await new Promise((resolve) => setTimeout(resolve, attempt * 250));
      }
    }
  }
  throw new Error(
    `Could not fetch icon for Wowhead item ${wowheadId}: ${String(lastError)}`,
  );
};

const results: Array<{ wowheadId: number; icon: string }> = [];
let cursor = 0;
const workers = Array.from(
  { length: Math.min(MAX_CONCURRENT_REQUESTS, wowheadIds.length) },
  async () => {
    while (cursor < wowheadIds.length) {
      const index = cursor;
      cursor += 1;
      const result = await fetchIcon(wowheadIds[index]);
      results.push(result);
    }
  },
);
await Promise.all(workers);
results.sort((left, right) => left.wowheadId - right.wowheadId);

const outputDirectory = new URL("../src/data/generated/", import.meta.url);
const outputFile = new URL("canonicalItemIcons.ts", outputDirectory);
const entries = results
  .map(({ wowheadId, icon }) => `  ${wowheadId}: ${JSON.stringify(icon)},`)
  .join("\n");
const source = `// Generated by scripts/sync-item-icons.ts from Wowhead Classic tooltip data.
// Run \`npm run sync:item-icons\` after adding raid items or canonical Wowhead IDs.
export const CANONICAL_ITEM_ICON_BY_WOWHEAD_ID: Readonly<
  Record<number, string>
> = Object.freeze({
${entries}
});
`;

await mkdir(outputDirectory, { recursive: true });
await writeFile(outputFile, source, "utf8");
console.log(
  `Synced ${results.length} canonical item icons at ${outputFile.pathname}.`,
);
